### ISSUE TITLE
[13] stock_mts_mto_rule does not include procurement from MO

### ISSUE THREAD

**Issue by alyngsoe** [OCA/stock-logistics-warehouse#1058]
The module works perfectly when you have a demand of a product from a salesorder, and want to use the new route. BUT if you have a manufacturing order and this creates a demand for for example af purchase, then the route is not working.

**Comment by alan196** [comment]
I have fixed this issue in V14 with this PR https://github.com/OCA/stock-logistics-warehouse/pull/1301
