### ISSUE TITLE
[stock_reserve_sale] doesnot depend on stock_ownership

### ISSUE THREAD

**Issue by elicoidal** [OCA/stock-logistics-warehouse#106]
Is this a good idea?
What if you need the module ownership for legacy reason reason (or any other module depending on it)?
Ideally would be to be depending on this module.

**Comment by pedrobaeza** [comment]
@lepistone or @gurneyalex seem to be the original authors, so maybe they can answer.

**Comment by lepistone** [comment]
I don't know myself. Maybe @gurneyalex . Thanks!
