### ISSUE TITLE
stock_inventory_location - How this module works ? 

### ISSUE THREAD

**Issue by legalsylvain** [OCA/stock-logistics-warehouse#108]
Hi, 

I'm just discovering the module stock_inventory_location that manages 'exhaustive' inventory. 
I don't understand how it works. 

**Use case 1**

My (shelf1) location is empty.
When I confirm the exhaustive inventory, a new pop up is opened with the following message.  "The following Locations are empty". After confirm, the inventory is filled with all the products presents in the location.
![empty](https://cloud.githubusercontent.com/assets/3407482/11498518/2ea0fe4c-9820-11e5-881b-c45aa6e14801.png)

-> OK.

**Use case 2**

My (shelf1) location has 1 product.
When I confirm the exhaustive inventory, the inventory is not filled automatically.

-> That is not the expected feature. (I expect that the inventory is filled with missing products). Did I miss something ?

CC : Numerigraphe.

**Comment by pedrobaeza** [comment]
@clonedagain, can you answer this, please?

**Comment by clonedagain** [comment]
`stock_inventory_location` does not change the way the inventory is filled, you still have to fill it using wizards or manual input.
What the module does is warn you when there's not data for a location, and if you confirm, remove existing stocks at this location from the system.
Does it answer your question ?

**Comment by clonedagain** [comment]
CC @lbellier
