### ISSUE TITLE
[14.0] stock_inventory_include_exhausted test failling after changes upstream

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/stock-logistics-warehouse#1102]
After this commit https://github.com/odoo/odoo/commit/b7e7029829915581056f3d79a36e3c2f60cc02f2 test are failling and travis is affected for all new pull requests.

@CarlosRoca13 you are the author, could you have a look?

**Comment by CarlosRoca13** [comment]
Yes sure, thanks for your notice

**Comment by CarlosRoca13** [comment]
I'm seeing that this module was added to odoo 14 https://github.com/OCA/OCB/blob/14.0/addons/stock/models/stock_inventory.py/#L62-L65 So I will remove this module on 14 and add it to OpenUpgrade
