### ISSUE TITLE
stock_mts_mto_rule :: extra moves created when recreate delivery order

### ISSUE THREAD

**Issue by ghost** [OCA/stock-logistics-warehouse#111]
product A = 5 units ( in stock)
make product A ( MTO+MTS )
make new sale order and order 10 units of product A
confirm and recheck availability in delivery order
confirm and receive products from the PO made
cancel the delivery order and recreate it from sale order
!!! now delivery order has extra lines

**Comment by levkar** [comment]
I confirm this bug but more. You don't even have to confirm and receive PO. Just cancel delivery order and recreate it from the sale order to see the magic.

Things really get serious once a customer realises that he gave some duplicate orders! 

FYI
@florian-dacosta @pedrobaeza

**Comment by StefanRijnhart** [comment]
Closing as the issue of duplicate lines was fixed in the attached PR
