### ISSUE TITLE
[8.0][stock_mts_mto_rule] move by mts_mto does not propagate

### ISSUE THREAD

**Issue by JulioSerna** [OCA/stock-logistics-warehouse#112]
Impacted version
- 8.0

Steps to reproduce
- To set warehouse **Outgoing Shippings** in three steps **pick/pack/out**
- To set warehouse with **Use MTS+MTO rule**
- To set one product with routes **Manufacture and Make to Order-Make to Stock**
- To set stock available of product with qty_available=10
- To create sale order with product_qty = 15

Current Behavior
When confirm sale order created the procurements and the procurements created:
- **Pick** with 2 lines,
  first line with product qty = 10 in waiting state
  second line with product qty = 5 in waiting another move
- **Pack and Out** with one line by 15 in waiting another move state
- And Manufacture Order by product qty=5

If MO is canceled the second line of the **pick** is canceled, but the all  **pack and out** is canceled also

Expected Behavior
I think the move created by mts-mto should be created in the pack and out also, in this way when cancel buy/manufacture only move by mts-mto is canceled in pick/pack/out

**Comment by JulioSerna** [comment]
I propose with this PR https://github.com/OCA/stock-logistics-warehouse/pull/113  when the warehouse is with "Use MTS+MTO rule" set by default the pull rule of customer location with split_procurement,
![warehouse s routes odoo](https://cloud.githubusercontent.com/assets/7595505/12130428/d0aa4e6c-b3cf-11e5-8400-1b07063b918d.png)

and the pick/pack/out  looks like this,

Pick,
![stock operations odoo](https://cloud.githubusercontent.com/assets/7595505/12130362/69fbe810-b3cf-11e5-98d6-396c35a920c8.png)
Pack,
![pickin_pack](https://cloud.githubusercontent.com/assets/7595505/12130367/7165d03e-b3cf-11e5-9878-3131c03da975.png)
Out,
![picking_delivery](https://cloud.githubusercontent.com/assets/7595505/12130369/76c39f84-b3cf-11e5-8637-1c7fa2714407.png)

**Comment by nhomar** [comment]
Closed here:

https://github.com/OCA/stock-logistics-warehouse/pull/113
