### ISSUE TITLE
Odoo package list

### ISSUE THREAD

**Issue by iman-alhaddar** [OCA/stock-logistics-warehouse#1122]
Impacted versions: 13.0

Steps to reproduce: Go to Inventory> then master data> then packages.

Current behavior: We will find that there is no data except for the (Company , Owner, Location, and the content which is Product, L/S number , quantity, unit of measure).

Expected behavior: We want to define more info like to add the gross and net weight and we need to print all the report in QR code instead of barcode.

If there is any module can help please inform me.
Thanks,

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
