### ISSUE TITLE
[13.0][stock_available] Unable to select any options in settings

### ISSUE THREAD

**Issue by ghost** [OCA/stock-logistics-warehouse#1155]
I recently installed both the stock_available and [website_sale_stock_available](https://github.com/OCA/e-commerce/tree/13.0/website_sale_stock_available) modules (version 13) on our Odoo install (Odoo 13.0-20200629 (Community Edition)) and have found they are not working as expected.

When follow the readme for the website_sale_stock_available module it states:
> Go to Inventory > Configuration > Settings, navigate to Stock available to promise section and set the desired option. If you do not choose any, the value of 'Available' quantity will be equal to 'Forecasted' quantity.

However when we select either of the tick boxes (and click save), they remain unticked on refresh of the page.
We have installed the correct versions of the modules and they install without error.

Any guidance would be appreciated. 
I also have an issue open on the website_sale_stock_available repo, [544]( https://github.com/OCA/e-commerce/issues/544)

**Comment by pedrobaeza** [comment]
That's because they require extra modules to be put on your addons path, and I'm not sure right now if they are already migrated.

@StefanRijnhart this is the problem we talked the other day about putting configuration options for installing extra modules.

**Comment by Flowbird-Ltd** [comment]
Hi @omeliailiffe you can manually install the modules below to solve this
https://github.com/OCA/stock-logistics-warehouse/tree/13.0/stock_available_mrp
https://github.com/OCA/stock-logistics-warehouse/tree/13.0/stock_available_immediately
