### ISSUE TITLE
qty shown in WO of Product mix unit of same category (ex Kg and g)

### ISSUE THREAD

**Issue by nikkocasa** [OCA/stock-logistics-warehouse#1187]
module: stock_quant_manual_assign
version: 12.0

**Steps to reproduce**
- set a BOM with a product defined as using Kg as main unit, but set requested value in grams in the BOM
- make an workorder unsing this BOM

**Current behavior**
- see that the wizard display values on the tree line with "on hand" in Kg but 'reserved' and 'selected' in gram

**Expected behavior**
- All the value have to be converted in the same unit (or base unit (Kg) or the one used in current WO (g)

**Comment by pedrobaeza** [comment]
AFAIK, this module is not suitable for manufacturing.

**Comment by nikkocasa** [comment]
Ah! Ok, thanks for the information - no information int the module's description on this fact.
But the ** mrp_production_quant_manual_assign ** module is based on it and does not contain any additional python code.
Therefore :
1. Should the bug report be passed to the mrp_production_quant_manual_assign module?
2. As far as I saw in the python code of the wizard, an improvement change could be made
    - adding 'uom' columns after that of each value (I tested it for lot's quant)
    - by displaying the values ​​of each ('reserved' and 'qty') calculated with uom_factor
    

I'm not familiar enough with OCA procedures and with some part of the code to do it on my own, but I can help with this.Nicolas
