### ISSUE TITLE
Cannot create secondary stock unit

### ISSUE THREAD

**Issue by Maurice67205** [OCA/stock-logistics-warehouse#1195]
odoo 13.0
I installed product_secondary_unit and stiock_secondary_unit module
the field secondary unit for inventory is appearing but i'm unable to enter any data and I get the message 'No results to show" on that field
can you please help me on that topic
regards
Maurice

**Comment by pedrobaeza** [comment]
Create first the secondary unit in its respective table inside the product itself.

**Comment by Maurice67205** [comment]
Thanks but it doesnt work for me
Could you please drop a little video or screen shots ?

**Comment by pedrobaeza** [comment]
Follow the instructions on the README:

https://github.com/OCA/product-attribute/blob/13.0/product_secondary_unit/README.rst

**Comment by Maurice67205** [comment]
I managed to get it working by removing the module stock_secondary_unit
Now I have a product with unit = kg and secondary unit = m with a factor 5
then I reinstalled stock_security_unit, but when I have 10 kg of  a product, the system displays 0 as number of secondary_unit

**Comment by Maurice67205** [comment]
Oups, sorry again I was missing the secondary unit on the product in the stock tab
Everything is fine now
many thanks for your help
