### ISSUE TITLE
[14.0] stock_move_location needs system rights

### ISSUE THREAD

**Issue by remi-filament** [OCA/stock-logistics-warehouse#1233]
Today, after installing stock_move_location on v14.0,
I realized that when clicking on Immediate transfer or Planned transfer on the wizard, an authorization error was raised for a non admin user, stating that it needs access to action_window.

These accesses have been removed in v14 (these were allowed on previous versions) with https://github.com/odoo/odoo/commit/de4213b771f641cbc218ebb1f759b09e064100bf#diff-e275aaa5de11da2815c2f0cc18bc046f967df5e4eba94999ee55ffe8926c87bd

Therefore the module should be reworked to create directly the action to be executed when clicking the buttons rather than trying to read an existing one for modifying it afterwards here : https://github.com/OCA/stock-logistics-warehouse/blob/183fb6443bdbfbe6a98415b4a356b1d376ec6117/stock_move_location/wizard/stock_move_location.py#L225

Also, I have noticed some other issues, which are not so critical. or possible improvements, I list them here since these might be tackled at the same time : 

- [x] IMP : origin and / or destination location could be filled from operation type if specified (#1237)
- [ ] IMP : add product in move line tree is not needed and confusing since all products in source locations are already filled, therefore adding a product from another location makes no sense since it will cause the picking to fail, also the tree view shown when clicking on add product only list IDs without other columns, which is not useable --> add product may need to be removed

**Comment by pedrobaeza** [comment]
I think simply putting `sudo` can serve, isn't it?

**Comment by remi-filament** [comment]
Sure, but I suppose these accesses have been removed for a reason, so I am not sure bypassing these with sudo is the best way to go, you should rather create a new action from scratch I guess ?

**Comment by pedrobaeza** [comment]
They have been removed for avoiding general data leak, but accessing in our module code is not a problem nor leak.

**Comment by remi-filament** [comment]
Fixed with #1326 
#1237 brings the first improvement reported in issue
