### ISSUE TITLE
stock_available_mrp

### ISSUE THREAD

**Issue by farazbdm** [OCA/stock-logistics-warehouse#1235]
stock_available_mrp > models > product>product.py > line 112

If by chance an empty BOM is created for a Product, i.e. without components.

Then this Product Form view cannot be opened anymore, or any area where stock_available_mrp reflects the quantity available based on BOMs.
and raises following error:

***************
addons/stock_available/models/product_template.py", line 26, in _compute_available_quantities_dict
    "product_variant_ids"
  File "/mnt/extra-addons/stock_available_sale/models/product_product.py", line 34, in _compute_available_quantities_dict
    self)._compute_available_quantities_dict()
  File "/mnt/extra-addons/stock_available_mrp/models/product_product.py", line 112, in _compute_available_quantities_dict
    immediately_usable_qty = potential_qty if bom_id.type != "phantom" else 0
UnboundLocalError: local variable 'bom_id' referenced before assignment
*********************

**Comment by rousseldenis** [comment]
@farazda1 Could you say what version you use?

**Comment by farazbdm** [comment]
@rousseldenis v13

**Comment by rousseldenis** [comment]
@victoralmau @chienandalu

**Comment by rousseldenis** [comment]
I think this corrected problem : https://github.com/OCA/stock-logistics-warehouse/pull/1248

@chienandalu correct ?

**Comment by chienandalu** [comment]
Yeah. Looks like it :slightly_smiling_face:
