### ISSUE TITLE
[RFC][14.0][stock_location_warehouse]

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/stock-logistics-warehouse#1250]
It is often necessary to know what is the warehouse associated with a location. Currently this connection does not exist and has to be calculated.

This new module would add the field 'warehouse_id' to the stock.location model as a computed, stored field. The computed field would be recomputed with an @api.depends('parent_id'), so that every time that the parent location changes, the warehouse is recomputed. But not only would the warehouse of the location that is changing be recomputed. Also upon recomputation all the child locations below the location that is changing would need to see their warehouse_id field recomputed.

@ForgeFlow

**Comment by rousseldenis** [comment]
Has been done there : https://github.com/OCA/stock-logistics-warehouse/pull/1258
