### ISSUE TITLE
[14.0] stock_move_location - consignment stock

### ISSUE THREAD

**Issue by mattmutex** [OCA/stock-logistics-warehouse#1281]
If you use consignment to setup the owner of a product when you receive it you cannot transfer a quant directly to another location using "immediate" transfer

The owner_id is missing somewhere so when you try to move directly a quant that is assigned with a partner (owner_id) the quant is not found and it makes a negative stock

**Comment by rousseldenis** [comment]
@joao-p-marques @LoisRForgeFlow

**Comment by LoisRForgeFlow** [comment]
Hey, 

This is true, it is not supported right now. Feel free to open a PR improving it.
