### ISSUE TITLE
[stock_mts_mto_rule]: MTO Procurement goes on exception with "No rule matching this procurement" message

### ISSUE THREAD

**Issue by aignermi** [OCA/stock-logistics-warehouse#130]
We have products configured as MTS+MTO, suppliers are set on the product and when I create a sales order, Odoo also creates the procurement but the procurement goes on status exception with "No rule matching this procurement" message. When I edit the procurement and add the "YourCompany:  Buy" rule to it, it runs through and creates the PO as it should. But I don't find the setting where I can set it that it inherits this setting for all future procurements. Any ideas?

**Comment by florian-dacosta** [comment]
I guess you have a configuration problem.
Did you check the box "'Use MTO+MTS rules" on your warehouse?

**Comment by aignermi** [comment]
Yes I did, the problem was that I also needed to set the Buy route on the product, so both: Buy & MTO&MTS Route pre product.
