### ISSUE TITLE
[stock_mts_mto_rule]: Multi Warehouse?

### ISSUE THREAD

**Issue by aignermi** [OCA/stock-logistics-warehouse#131]
Is the stock_mts_mto_rule module multi warehouse able? If yes, what is the correct way to set that up? Do I duplicate the MTS+MTO Route and set than on the product in which warehouse the po should be delivered? Thx for your help!

**Comment by florian-dacosta** [comment]
I have never tested the module with multiwarehouse, but I guess it should work if you configure it well.
You should not duplicate the mts+mto route, it won't work this way.

When you create your new warehouse, you should have a new mts rule and a new mto rule for this warehouse.
Then, you can duplicate the mts+mto rule (inside the mts+mto route), configure it with the new warehouse, the new mts rule and the new mto rule.

The system will chose the right pull rule depending on the warehouse.

The same product could be deliver in wharehouse 1 ou 2 depending on the procurement's warehouse.

**Comment by aignermi** [comment]
it actually works like a charm like you described, thanks @florian-dacosta !
