### ISSUE TITLE
[15.0] stock.inventory model disappeared in V15

### ISSUE THREAD

**Issue by legalsylvain** [OCA/stock-logistics-warehouse#1328]
Hi all,

In V15, seems that ``stock.inventory`` model disappeared.
The screen "inventory adjustment" is now a tree editable view on stock quant.

![image](https://user-images.githubusercontent.com/3407482/145968145-1994a95a-ec72-4445-91de-24e3d9c1d8b3.png)

I don't understand that feature move.
I don't understand how it's possible to make a partial inventory, per location, or a full inventory with a lot of products.
some one faced to that problem ? 
have ``stock.inventory`` moved to EE ?

thanks for your answer.

**Comment by rousseldenis** [comment]
At first sight, nothing on EE on that point.

I think we need to check that for sure!

**Comment by rousseldenis** [comment]
Mmmh, indeed. I think they did that for performances reasons. But that's a step back in terms of usability. That's possible to do for small warehouses with few products...

**Comment by rousseldenis** [comment]
Arf, if you want usability, you can now ... import quants directly ... WTF

https://github.com/odoo/odoo/commit/04beff906de89895926799ecbae605ce2e38e951#diff-7d271dc8cd91058e14e1677a1c6e17d155106fa88ccd0dce46ec8c345a38b91d

**Comment by legalsylvain** [comment]
hum... what about a module named ``stock_inventory`` in that repo ? ;-)

**Comment by rousseldenis** [comment]
Of course. The advantage: we'll have the power on that part to make it better than the deprecated one.

**Comment by rousseldenis** [comment]
I would tend to create a new repository for that as there are some modules for that) . I will call it.

**Comment by legalsylvain** [comment]
Nice. what about to define limitations of the current module.

I have some criticisms about the current workflow. like [this one](https://github.com/odoo/odoo/pull/81364) for exemple.

**Comment by cvinh** [comment]
Odoo did a video about inventory adjustments in v15 here https://youtu.be/GP3bmOrYnTg

**Comment by legalsylvain** [comment]
Thanks @cvinh for the link.
note : this video is horrible ! It lasts 25 minutes for 3 interesting informations, and 15 average jokes... ;-)

**Comment by legalsylvain** [comment]
Cc : @sebastienbeau
