### ISSUE TITLE
stock_mts_mto issue

### ISSUE THREAD

**Issue by jaronemo** [OCA/stock-logistics-warehouse#133]
step:
1、warehouse set use mts+mto in multi warehouse
2、product ...procurement sheet set use  mts+mto rule
3、run procurement ...error
![image](https://cloud.githubusercontent.com/assets/8476734/13692741/1703f876-e77f-11e5-9781-52ede21e7dbf.png)
![image](https://cloud.githubusercontent.com/assets/8476734/13692750/294a8c84-e77f-11e5-8d6e-def81f5e9765.png)
4、go product --> procurement sheet ...don't use mts+mto 
5、go warehouse --> run procurement ---> it's ok...

**Comment by florian-dacosta** [comment]
It must be a configuration issue with your mts+mto rule.
What is the procurement location of your mts+mto rule?
What is the procurement location and the source location of the MTO rule configured inside the mts+mto rule?
What is the procurement location and the source location of the MTS rule configured inside the mts+mto rule?

**Comment by jaronemo** [comment]
Dears:
I find problem..about this
procurement rule in mts rule and mto rule ...location..is null 
But. I dont know...why?

**Comment by anajuaristi** [comment]
I'm trying to configure mts+mto for 2 steps outgoing warehouse and I find no way. 

The use case is this one

I want to move materials from stock --> output --> customers

I need to configure mts+mto only on first step
i select mts+mto on warehouse so a new route is created but the Mts and Mto correctly created rules are for output location. On customers location I have got the same rule (MTO) on both fields.
If I let it like created by default, it is never selecting materials from stock,
If I create manually the MTS rule for customers location and set it on MTS field on route, It's always applying MTS so it's not creating the internal picking from stock to output. 

I tried to create minimun stock rules and I tried to configure in several ways but I never can obtain the sale order line splited in 2 lines, same way that it's working on sales order to be procured from purchases. 
Any help would be appreciated.
Thank you:
Ana

**Comment by florian-dacosta** [comment]
I guess for your use case, you should have : 

One pull rule with procurement location : Customers and Source location : Output. (let's call it customer rule)
Another MTS pull rule with procurement location Output and source location stock. (let's call it mts rule)
An equivalent MTO rule with procurement location Output and source location stock.(let's call it mto rule)

A MTS+MTO rule with : 
- procurement location : Output
  mto rule => the previous mto rule
  mts rule => the previous mts rule.

This way, i you check the mts+mto route on the product form for example, when you validate an order it will : 
Create a procurement on customer location that will find the customer rule.
This procurement will create a move output => custom That will create another procurement on output location.
This second procurement will choose the right rule depending on the route configured.
It could take the MTO rule, to make a classic PO without checking the virtual stock
It could take the mts rule and nothing happen.
It could take the mts+mto rule that will check the stock and split into one or two procurement. (the mto and mts configured previously).
So if mts+mto rule is chosen and we need stock, a purchase order will be created on stock. location (if the buy rule has 'stock' as its procurement location.)

If I understood you use case, it should work.
I use it for a 4 steps outgoing warehouse and it works fine.

**Comment by pedrobaeza** [comment]
Answered, so I close.
