### ISSUE TITLE
Migrate stock_inventory_hierarchical and stock_inventory_location to v8

### ISSUE THREAD

**Issue by clonedagain** [OCA/stock-logistics-warehouse#134]
We're finally migrating these 2 modules to v8.
When this is done, migration to v9 "should" be quite simple.
# History
- [x] pull the history of the modules into the branch `8.0` - 
# `stock_inventory_hierarchical`
- [x] PR: https://github.com/OCA/stock-logistics-warehouse/pull/139
- [x] use `location_id` (now it's standard)
- [x] move the "generate inventories" wizard to  `stock_inventory_hierarchical` (drop the field `exhaustive`)
- [x] improve the automatic tests
- [x] migrate to API v8
- [x] update translations
- [x] follow the newest OCA conventions
- [x] update the screenshots
- [x] add the screenshots to the README
- [x] Rewrite the tests in python and complement them
# `stock_inventory_location`
- [ ] PR: https://github.com/OCA/stock-logistics-warehouse/pull/155
- [x] PR for location lockdown: https://github.com/OCA/stock-logistics-warehouse/pull/149
- [x] drop the extra state `open` if possible
- [x] make sure `location_id` is correctly used (now it's standard)
- [x] adapt to the new way of filling inventories (no more wizard to do this)
- [x] change the messages on bottom of inventory form
- [x] migrate to API v8
- [x] update translations
- [x] follow the newest OCA conventions
- [x] update the screenshots
- [x] add the screenshots to the README
- [x] Rewrite the tests in python and complement them
## `stock_inventory_hierarchical_location`
- [x] inherit the "generate inventories" wizard to from `stock_inventory_hierarchical` to add the field `exhaustive`
- [x] Rewrite the tests in python and complement them

**Comment by clonedagain** [comment]
@laetitia-gangloff @lmignon @sbidoul for your information

**Comment by clonedagain** [comment]
All PRs have been posted, reviewers wanted.

**Comment by pedrobaeza** [comment]
I close this issue as the PRs are done
