### ISSUE TITLE
Multi Line Stock Request or Stock Distribution Order

### ISSUE THREAD

**Issue by bunhin** [OCA/stock-logistics-warehouse#1382]
**Is your feature request related to a problem?**

While Purchase Order and Sales Order are avilable in core, I believe there is not yet availble for Stock Distribution (Transfer) Requst.
I see the the stock_request module as a potenstial candidate for enhancement to cover distribution order or request. 

**Describe the solution you'd like**

A quick and efficient way to distribute stock from a warehouse to one or many warehouses with request approval
A requester should able to create a multiline transfer request to a source warehouse
For each request line, a product is selected from list of candidates, qty requested for transfer is filled by user (one warehouse for each column in the same line) -->may be using [web_widget_x2many_2d_matrix  that OCA already have.
Once it is filled, the requester may need approval, once approved he/she will sumbit so the request will shown to the source warehouse manager. The manager to put approval or rejection of the request or approve partially
Once approved stock picking is created for each destination warehouse.

Stock_request module seem a potential for the purpose but need some enhancement because the module is not for multi line request at the moment.

**Describe alternatives you've considered**
Create multi transfer (picking) wizard using [web_widget_x2many_2d_matrix],  where product in header or first other matrix, source and destination warehouse in second matrix, each cell filled with a quantity to transfer  (if positif number the transfer is from eg for row warehouse, if negatif to the row warehouse)

**Comment by JordiBForgeFlow** [comment]
@bunhin stock request does allow multi line request. You just have to activate it in the Settings of the Stock Request module

**Comment by bunhin** [comment]
Oh Ok, Thank you @JordiBForgeFlow , i will explore more then. I see, it is under stock request order, can multiline

**Comment by bunhin** [comment]
I found it very powerful then, and forseeing further enhancement like purchase_location_by_line (stock request order destination by line), in combination with a wizard using web_widget_x2many_2d_matrix. I see a use case for stock pulling and balancing (usualy a retail merchandiser use it). To instruct distribution from central warehouse over store warehouses, to spot quickly which item is not selling or slow selling rate in a location, then transfer to higher selling rate location, or to pull it back uncomplete option range (color or size) for many location then recombine make it complete then redistribute. Because usually working with a lot off items powerfull wizard is key to make speed.
