### ISSUE TITLE
[RFC] generating miscellaneous account move when confirming picking

### ISSUE THREAD

**Issue by legalsylvain** [OCA/stock-logistics-warehouse#1388]
Hi all, 

I have the following recurring need for my company (GRAP, grocery cooperative)

Most of the products purchased are for resale. So my global settings for products is to set a expense account (french) "607 - purchase of goods".

However, regurlarly grocers will "use" products for other purpose : 
- take cleaning products out of stock to wash the store. (60222 - cleaning products)
- to take out food products to make tastings to the customers. ( 6232 - tastings for customers)
- etc. 

In that case, I have two needs when confirming the picking : 
- logistic one : Remove products from stock and place them in a scrap location.
- accounting one : generate a miscellaneous account move : 

- 607 - purchase of goods - Debit 100€
- 6232 - tastings for customers - Credit 100€

Do you have similar needs ? Do you know how to handle that workflow in Odoo ? do you know OCA modules for that purpose ?

for the time being, I used a incubated module ``stock_internal_use_of_products``. ([Ref](https://github.com/grap/grap-odoo-incubator/tree/12.0/stock_internal_use_of_products)) but I think I could reuse ``stock.picking.type`` and so, having something more standards and "OCA shareable".

thanks for your remarks.

**Comment by alan196** [comment]
I use stock_request module to handle this situation.

First I create two locations of type scrap and define the accounts, for cleaning and testing.

I configure a pull stock rule to ask for this product from stock when is procured.

Then I make a stock request order to get the products in cleaning or testing.

The stock_request module make the picking and when you validate it you get the account move

Inventory 100€ credit
Cleaning 100€ debit

You transfer directly from inventory account and you don't transfer it from expense account

**Comment by legalsylvain** [comment]
Hi. Thanks for your answer, @alan196.

> Inventory 100€ credit
> Cleaning 100€ debit

I'm not sure to understand. Inventory is a an asset account so ? My objective is more to make an account move from the original expense account to a specific "cleaning" expense account. (that is an expense transfer).

(If I understand correctly) I think that your workflow works because you enabled real-time inventory valuation (Or maybe I missed something ?)

thanks.

**Comment by alan196** [comment]
Yes, the real-time inventory valuation is enabled.

When you receive the products it affects the inventory account, then when the product is transferred to any scrap location, it automatically makes the journal entries from inventory to the account defined in the location.

**Comment by legalsylvain** [comment]
hum. I didn't enable real-time inventory valuation and I don't want to. (to avoid to have billion of unncessary account move for each picking confirmed).

do you think if it could work in that case ?

regards, and thanks for your answer.
