### ISSUE TITLE
[13] stock_move_location: wrong evaluation company_id

### ISSUE THREAD

**Issue by jprokop1** [OCA/stock-logistics-warehouse#1420]
## Module
stock_move_location

In multicompany enviroment, if default user company is different as selected company, the location selection menu in wizard offers wrong values.

**Affected versions**: 13

In my opinion problem is the evaluation of company_id in wizard/stock_move_location.py, line 15:
`company_id = self.env.context.get("company_id") or self.env.user.company_id.id`
and line 122:
`("company_id", "=", self.env.user.company_id.id),`
I think it should be:
`self.env.company.id`

**Comment by rousseldenis** [comment]
Hi @jprokop1. Thanks for this. Can you do a PR to fix this?

**Comment by jprokop1** [comment]
Done - #1422
Thanks
