### ISSUE TITLE
scrap_reason_code : add reason group

### ISSUE THREAD

**Issue by mymage** [OCA/stock-logistics-warehouse#1468]
Hi, if you are in a domain where there are many scrap reasons it is convenient to have some sort of aggregation (ie Originated by Machine, Related to material, Operator fault, ...) for a synthetic analysis.

We can add this feature using this module in two way:
- defining a new model like scrap.reason.group.code and adding a group_id to scrap.reason.code (I like this)
- use the actual model adding a flag to identify group reasons and a reference to group scrap reason

I like the first because it is "simpler" to manage and you can extend properties, ie associate a department code to create specific group of reasons, without wheight down the model of the base reasons.

I would like your comments.

**Comment by marcelofrare** [comment]
I would do the same logic as product.category → parent_id on the same model
