### ISSUE TITLE
remstar, horizontal carousel

### ISSUE THREAD

**Issue by dipromed** [OCA/stock-logistics-warehouse#1478]
we are working with odoo 14, we acquired a remstar horizontal carousel and we would like to know if its module can be adapted for that equipment

**Comment by rousseldenis** [comment]
I think you should look here : https://github.com/OCA/stock-logistics-warehouse/tree/14.0/stock_vertical_lift_kardex

**Comment by rousseldenis** [comment]
@guewen @simahawk can certainly help you

**Comment by dipromed** [comment]
@guewen @simahawk how can i contact to you?

**Comment by simahawk** [comment]
> I think you should look here : https://github.com/OCA/stock-logistics-warehouse/tree/14.0/stock_vertical_lift_kardex

Yes, this is probably your starting point. 

To get in touch, just send us a message through the contact form you find here https://www.camptocamp.com/locations
