### ISSUE TITLE
'stock.quant' object has no attribute 'available_quantity'

### ISSUE THREAD

**Issue by amaiaMDNURRA** [OCA/stock-logistics-warehouse#1493]
Installing "stock_available_unreserved" it appers the Odoo Server Error "'stock.quant' object has no attribute 'available_quantity'". 
Reading depedencies this module only depends of stock module.
Can anyone tell me in which module is "available_quantity" field in "stock.quant" ?
Thank you.

**Comment by pedrobaeza** [comment]
You haven't installed it correctly. FYI, "Import module" option doesn't serve.

Closing as no module issue, but deployment one.

**Comment by amaiaMDNURRA** [comment]
I don`t use import module. Do you know where is declared "available_quantity"?

**Comment by pedrobaeza** [comment]
You haven't put Odoo version, nor the exact traceback, so with that information, nothing more can be said.
