### ISSUE TITLE
module stock_lock_lot throws exception when creating lot_id via xmlrpc

### ISSUE THREAD

**Issue by disna-sistemas** [OCA/stock-logistics-warehouse#150]
I have a script to import data via xmlrpc with the following code:

*\*                lot_values= {
                    'product_id': some_prod_id,
                    'name': some_lot,
                    'life_date': some_date,
                }

```
            lot_id = models.execute_kw(dbname, uid, pwd, 'stock.production.lot', 'create', [lot_values])**
```

It works while module stock_lock_lot is not installed, otherwise, odoo throws this exception:

xmlrpclib.Fault: <Fault 1: 'Traceback (most recent call last):\n  File "/opt/odoo/v8/core/openerp/service/wsgi_server.py", line 75, in xmlrpc_return\n    result = openerp.http.dispatch_rpc(service, method, params)\n  File "/opt/odoo/v8/core/openerp/http.py", line 115, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 37, in dispatch\n    res = fn(db, uid, *params)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 167, in execute_kw\n    return execute(db, uid, obj, method, *args, **kw or {})\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 118, in wrapper\n    return f(dbname, *args, **kwargs)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 175, in execute\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 164, in execute_cr\n    return getattr(object, method)(cr, uid, *args, **kw)\n  File "/opt/odoo/v8/core/openerp/api.py", line 268, in wrapper\n    return old_api(self, *args, **kwargs)\n  File "/opt/odoo/v8/other-addons/stock_lock_lot/models/stock_production_lot.py", line 72, in create\n    product_id = vals.get(\'product_id\', context.get(\'product_id\', False))\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'>

**Comment by clonedagain** [comment]
We'd need to have the exact error message you get, I'm not sure we can do much without that.
Can you provide that please ?

**Comment by clonedagain** [comment]
@lbellier maybe we'll want to look into this.

**Comment by disna-sistemas** [comment]
Sorry,   the thrown exception is:

/usr/bin/python2.7 "/opt/odoo/v8/disna-sistemas/xml-rpc/disna/inventario/991_inventario delferro semi.py"
{'server_version_info': [8, 0, 0, 'final', 0], 'server_serie': '8.0', 'server_version': '8.0', 'protocol_version': 1}
Traceback (most recent call last):
  File "/opt/odoo/v8/disna-sistemas/xml-rpc/disna/inventario/991_inventario delferro semi.py", line 110, in <module>
    lot_id = models.execute_kw(dbname, uid, pwd, 'stock.production.lot', 'create', [lot_values])
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(*_self._stack[0])
xmlrpclib.Fault: <Fault 1: 'Traceback (most recent call last):\n  File "/opt/odoo/v8/core/openerp/service/wsgi_server.py", line 75, in xmlrpc_return\n    result = openerp.http.dispatch_rpc(service, method, params)\n  File "/opt/odoo/v8/core/openerp/http.py", line 115, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 37, in dispatch\n    res = fn(db, uid, *params)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 167, in execute_kw\n    return execute(db, uid, obj, method, *args, *_kw or {})\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 118, in wrapper\n    return f(dbname, _args, *_kwargs)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 175, in execute\n    res = execute_cr(cr, uid, obj, method, _args, *_kw)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 164, in execute_cr\n    return getattr(object, method)(cr, uid, _args, *_kw)\n  File "/opt/odoo/v8/core/openerp/api.py", line 268, in wrapper\n    return old_api(self, _args, *_kwargs)\n  File "/opt/odoo/v8/github/OCA/stock-logistics-workflow/stock_lock_lot/models/stock_production_lot.py", line 72, in create\n    product_id = vals.get(\'product_id\', context.get(\'product_id\', False))\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'>

Process finished with exit code 1

**Comment by lbellier** [comment]
Hi @disna-sistemas,
Thanks for the complete traceback.
I can see that the last line indicated you try to create a lot with a product_id equal to False, so without any product.
Is this normal ?

**Comment by disna-sistemas** [comment]
Hi @Ibellier,
No, the product_id is always set, never False.  The code works perfectly if I uninstall this module, creating the lot for the proper product_id.

**Comment by lbellier** [comment]
Ok,
The traceback indicate the error was on line 72.
The last version indicate the line 81 for the same code.
Are you sure your code is up to date ?

**Comment by disna-sistemas** [comment]
Here you are the whole fully simplified code:

# -_\- encoding: utf-8 -_-

import xmlrpclib

url = 'http://192.168.25.21:8069'
common = xmlrpclib.ServerProxy('{}/xmlrpc/2/common'.format(url))

dbname='some_db'
username='admin'
pwd='some_password'

uid = common.authenticate(dbname,username,pwd,{})
models = xmlrpclib.ServerProxy('{}/xmlrpc/2/object'.format(url),allow_none=True)

lot_values= {
    'product_id': 7,
    'name': 'mylot',
}

lot_id = models.execute_kw(dbname, uid, pwd, 'stock.production.lot', 'create', [lot_values])

This works perfectly in a database without this module, but crashes if installed, I've just tested again.
The 2 minutes old exception:

Traceback (most recent call last):
  File "/opt/odoo/v8/disna-sistemas/xml-rpc/disna/inventario/991_inventario delferro semi.py", line 21, in <module>
    lot_id = models.execute_kw(dbname, uid, pwd, 'stock.production.lot', 'create', [lot_values])
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(*_self._stack[0])
xmlrpclib.Fault: <Fault 1: 'Traceback (most recent call last):\n  File "/opt/odoo/v8/core/openerp/service/wsgi_server.py", line 75, in xmlrpc_return\n    result = openerp.http.dispatch_rpc(service, method, params)\n  File "/opt/odoo/v8/core/openerp/http.py", line 115, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 37, in dispatch\n    res = fn(db, uid, *params)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 167, in execute_kw\n    return execute(db, uid, obj, method, *args, *_kw or {})\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 118, in wrapper\n    return f(dbname, _args, *_kwargs)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 175, in execute\n    res = execute_cr(cr, uid, obj, method, _args, *_kw)\n  File "/opt/odoo/v8/core/openerp/service/model.py", line 164, in execute_cr\n    return getattr(object, method)(cr, uid, _args, *_kw)\n  File "/opt/odoo/v8/core/openerp/api.py", line 268, in wrapper\n    return old_api(self, _args, *_kwargs)\n  File "/opt/odoo/v8/github/OCA/stock-logistics-workflow/stock_lock_lot/models/stock_production_lot.py", line 72, in create\n    product_id = vals.get(\'product_id\', context.get(\'product_id\', False))\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'>

Process finished with exit code 1

**Comment by lbellier** [comment]
@disna-sistemas.
You are right, our code have a bug.
You can find the new pull request at the following adress : 
https://github.com/OCA/stock-logistics-workflow/pull/214

**Comment by clonedagain** [comment]
Please close the issue: fixed at https://github.com/OCA/stock-logistics-workflow/commit/4e5ae1404e988945f365ecccbffc4847d474b46f.
