### ISSUE TITLE
v15- stock_quant_manual_assign: multi-uom error

### ISSUE THREAD

**Issue by alexis-via** [OCA/stock-logistics-warehouse#1527]
Module stock_quant_manual_assign on v15, on this line of code:
https://github.com/OCA/stock-logistics-warehouse/blob/15.0/stock_quant_manual_assign/wizard/assign_manual_quants.py#L67

```
ml.qty_done = ml.product_qty
```
where ml is an instance of stock.move.line.
AFAIK, on stock.move.line:
- qty_done is in product_uom_id
- product_uom_qty is in product_uom_id
- product_qty is in the product unit of measure

so we should write 
```
ml.qty_done = ml.product_uom_qty
```

**Comment by alexis-via** [comment]
same bug in mrp_production_quant_manual_assign from OCA/manufacture

**Comment by alexis-via** [comment]
To reproduce the bug, you need to create a picking manually and create a move line manually with a uom which is different from the product's uom.

**Comment by LoisRForgeFlow** [comment]
Solved here in v16 https://github.com/OCA/stock-logistics-warehouse/pull/1707.
