### ISSUE TITLE
16.0 - stock_move_location : not working in inventory adjustment

### ISSUE THREAD

**Issue by AungKoKoLin1997** [OCA/stock-logistics-warehouse#1578]
The name of the module that has a bug.
 -  stock_move_location

**Affected versions**: 16.0

Description:
 - There are two issues when move to location in inventory adjustment. The first one is when we change the "Quantitiy to move" and press enter.Then, it causes the virtual__xxx issue because of many2many field with one2many widget in wizard form and add line using (0,0, values) in default_get function. And the second one is when click "IMMEDIATE TRANSFER" or "PLANNED TRANSFER" button. This issue is caused when we don't enable unit of measure in setting and then face a trouble at float_compare because rounding is got from product_uom_id and there is no product_uom_id in this case.
 
Step to reproduce for first issue:

 - Go to Inventory > Operations > Inventory adjustments
 - Select a product and select action "move location" (you can see wizard)
 - Change the "Quantitiy to move" and click enter.
 
Step to reproduce for second issue:

 - Go to Inventory > Operations > Inventory adjustment
 - Select a product and select action "move location" (you can see wizard)
 - Click "IMMEDIATE TRANSFER" or "PLANNED TRANSFER" button.

Please see this reference for first issue:
https://drive.google.com/file/d/1PV1QwupWy__9CZg8XrDq14SnsBEiRMO4/view?usp=share_link

**Comment by AungKoKoLin1997** [comment]
For first issue, we can fix changing widget from one2many_list to one2many for the versions before v16.0. Unfortunately, it doesn't work in v16.0. Many2many field with one2many widget doesn't support for create="0" in tree tag of v16.0. I think this is the bug for v16.0.

**Comment by AungKoKoLin1997** [comment]
@rousseldenis @pedrobaeza Can you please give me your thoughts on first issue?

**Comment by pedrobaeza** [comment]
Uhm, I don't completely understand the issue as I don't know the internals of the module, but hearing many2many scratches me. Why not using a real one2many for such popup?
