### ISSUE TITLE
Any documentation on how to configure the mts+mto?

### ISSUE THREAD

**Issue by jtempletmg** [OCA/stock-logistics-warehouse#1603]
module: stock_mts_mto_rule
version: 14.0

The readme says to select MTS+MTO on the warehouse which I did.  When I try to save that change I'm getting the following error:

No MTS or MTO rule configured on procurement rule: SCM: Stock → Customers (MTS+MTO)!

That rule does not exist after installing the module.  So I assumed I would need to create one so I tried that.  I can see there is an action now called "Choose between MTS and MTO".  I'm not an expert on rules so I'm not exactly sure how this should be configured.  Any guidance on getting this set up?

**Comment by rousseldenis** [comment]
@florian-dacosta

**Comment by rousseldenis** [comment]
@jtempletmg I've just tested on runboat and it's working like a charm.

Maybe some misconfigurations on your instance ?
