### ISSUE TITLE
[14.0][stock_reserve_rule] the reserved lot is wrong

### ISSUE THREAD

**Issue by fa-odoo** [OCA/stock-logistics-warehouse#1616]
## Module
stock_reserve_rule

## Describe the bug
the reservation rule chose the right quant but does not affect the correct lot
## To Reproduce
**Affected versions**:14.0

1- Product A with two available lots:
       -lot 1: 12units on hand with removal date set to 12/12/2022
       -lot2: 24 units on hand with removal date set to 12/02/2023
2- apply the FEFO strategy
3- create a reservation rule as below:
![image](https://user-images.githubusercontent.com/42148719/214337233-3d398ea8-0ebc-4ec7-951f-baed59a344ad.png)
![image](https://user-images.githubusercontent.com/42148719/214337369-3627e980-f106-4a5b-9088-715f2b3dde0b.png)

**Expected behavior**
the right lot to reserve is the second, but it's the second one which is reserved on manifacturing

**Comment by rousseldenis** [comment]
@jbaudoux @sebalix @mt-software-de Could you help in this ?

**Comment by jbaudoux** [comment]
@fa-odoo You have not understood the module purpose.

The purpose is to decide from which location (i.e. zone) you want to reserve, and give rules on a list of possible locations. So having a rule on Stock does not make sense.
Once the location has been decided, then standard removal strategy will apply, like fifo/fefo.
