### ISSUE TITLE
MTS+MTO Rule Question:Create a duplicate of the same production ..Why?configure error?

### ISSUE THREAD

**Issue by jaronemo** [OCA/stock-logistics-warehouse#164]
Dears:
![image](https://cloud.githubusercontent.com/assets/8476734/15134555/d80d8c68-169f-11e6-8fae-5f82aeb21755.png)

It will generate similar production of single or repeated purchase orders every day, in different product items
I do not know that part of the configuration problem caused.
For example shown, block up the rules to generate the MO1 and MO2 single production

**Comment by AlainVanUtterbeeck** [comment]
![image](https://cloud.githubusercontent.com/assets/19188561/23058466/67710a4a-f4f5-11e6-9a9a-1055531f99ad.png)
tracebility of the products:
![image](https://cloud.githubusercontent.com/assets/19188561/23058608/1b728a3c-f4f6-11e6-96c5-522f82d2eafb.png)
Could it be there is someting wrong in the combination of using:
- warehouse setting: Bring goods to output location before shipping (Pick + Ship)
- mto + mts rule on the product
Apparantly, I get double requirements, what of course is very dangerous
Anyone got any ideas what we're doing wrong?
