### ISSUE TITLE
odoo exception 'The requested operation cannot be processed because of a programming error setting the `product_qty` field instead of the `product_uom_qty`

### ISSUE THREAD

**Issue by jerzyk** [OCA/stock-logistics-warehouse#1642]
during stock move operations, odoo raises exception:

'The requested operation cannot be processed because of a programming error setting the `product_qty` field instead of the `product_uom_qty`

## Module
stock_request

## Describe the bug
code is assigning computed quantity to the computed field in stock_request/models/stock_request_abstract.py line 34 (`_compute_product_qty` method)

## To Reproduce
**Affected versions**:
15+

**Comment by rousseldenis** [comment]
@jerzyk The code seems correct. It seems the error comes from elsewhere.

Could you copy paste the complete traceback you had ?

**Comment by jerzyk** [comment]
no traceback - this is UserError raised from addons/stock/models/stock_move.py L372 (_set_product_qty)

**Comment by rousseldenis** [comment]
> no traceback - this is UserError raised from addons/stock/models/stock_move.py L372 (_set_product_qty)

It seems all code lines are covered with tests and this module is widely used. Are you sure you don't have any other module that can cause the issue ?

**Comment by jerzyk** [comment]
pretty sure, this is the only one place (except odoo standard) where product_qty is set, plus after uninstalling this module (stock_request) error is not shown...

I'll try today to download db from odoo.sh and debug it locally to get better understand this issue, this error is only on R15 (R14 works fine)

**Comment by jerzyk** [comment]
I'm closing this - error was resolved by itself after updating odoo to latest 15.0 code
