### ISSUE TITLE
sort order in stock.picking override in stock_exception changes all standard views

### ISSUE THREAD

**Issue by jerzyk** [OCA/stock-logistics-warehouse#1721]
## Module
stock_exception

## Describe the bug
this module overrides sort oder for stock.picking model - but this affect all the existing views 

**Expected behavior**
this module should implement minimal changes that are needed, without breaking existing functionalities

additional sort order could be implemented as options to be selected from specific views as an addition to basic functionality

**Comment by rousseldenis** [comment]
@jerzyk Could you explain which version of the module you use ?

**Comment by jerzyk** [comment]
version: 14.0.1.0.1 (stock_exception is not ported yet to 15 & 16)

**Comment by rousseldenis** [comment]
Indeed, missed that. It's in fact better to :
- Never change base models _order property
- Change instead the order in xml view
- Do another picking view and action (best)

@newtratip @Saran440

**Comment by Saran440** [comment]
@jerzyk  Do you mean issue from https://github.com/OCA/stock-logistics-warehouse/blob/14.0/stock_exception/models/stock.py#L10 ?

I agree with option `Do another picking view and action (best)`

**Comment by jerzyk** [comment]
> @jerzyk Do you mean issue from https://github.com/OCA/stock-logistics-warehouse/blob/14.0/stock_exception/models/stock.py#L10 ?

yes!
