### ISSUE TITLE
16.0 stock_quant_manual_assign - a mandatory field is not set

### ISSUE THREAD

**Issue by BT-jmichaud** [OCA/stock-logistics-warehouse#1736]
## Module
stock_quant_manual_assign

## Describe the bug
The module itself is not working. The goal of this module is to select quant or part of quants to be moved. When I try to select manually a quant, I get the following error:

_The operation cannot be completed:
- Create/update: a mandatory field is not set.
- Delete: another model requires the record being deleted. If possible, archive it instead.

Model: Assign Manual Quants Lines (assign.manual.quants.lines)
Field: Move (assign_wizard)_

## To Reproduce
16.0

1. Create 2 location under WH/Stock (WH/Stock/loc1 and WH/Stock/loc2)
2. Create a product followed by lot. 
3. Create 2 lots for the product and add qty for both lot of the product in loc1
4. Create a planned internal transfer from loc1 to loc2
5. Launch the wizard of stock_quant_manual_assign
6. click on "Select" --> Error

**Expected behavior**
It should simply do what it has to

**Additional context**
Tested on a new Odoo 16.0 without any other module that what this module requires.

**Comment by bruno-zanotti** [comment]
Hi @BT-jmichaud I think the PR https://github.com/OCA/stock-logistics-warehouse/pull/1792 solves this issue..  it seems there is a bug related to the widget boolean_toggle.. would you check it?

**Comment by BT-jmichaud** [comment]
@Bruno-Zanotti Yes the PR you mentioned is fixing it. Thank you for informing me.
