### ISSUE TITLE
stock_quant_manual_assign...performance issue

### ISSUE THREAD

**Issue by jaronemo** [OCA/stock-logistics-warehouse#175]
Dears:

When the module is installed.

Serious performance problems occur when picking a job.
Create a picking document contains only a sum of product information, save time, have to spend 5 to 8 minutes or so to complete the save.

After removal of this module, the job was within 1 second.

**Comment by pedrobaeza** [comment]
AFAIK, this module doesn't impact in that operation, so please re-check.

**Comment by jaronemo** [comment]
Dears

In facts, True.
We took two test database, each on a different machine. This module are installed.
A database: a large amount of documents under practical circumstances, he is able to issue effective on.
B database: use demo data, no this question.

In addition, A database has multiple warehouses. WH1 ~ WH7
There will be the amount of documents and multi-WH1 ~ WH3 amount of stock movement is also large case

WH6 ~ least (example demo data) .. would not have this problem

use db log level get..this status

2016-07-04 00:18:56,279 805 DEBUG PROD openerp.sql_db: query: SELECT "stock_move"."picking_type_id","stock_move"."id" FROM "stock_move"

WHERE "stock_move".id IN (188416, 188418, 188420, 188431, 188433, 188435, 188437, 188439, 188441, 188443, 188445, 188447, 188449, 188451, 188453, 188455, 188457, 188461, 188467, 188469, 188471, 188473, 188475, 188477, 188479, 188481, 188485, 188487, 188489, 188523, 57452, 188525, 57454, 188527, 57456, 188529, 57458, 188531, 57460, 188533, 57462, 188535, 57464, 188537, 57466, 188539, 57468, 188541, 57470, 188543, 57472, 188545, 57474, 188547, 57476, 188549, 57478, 188551, 57480, 188553, 57482, 188555, 57484, 188557, 57486, 188559, 57488, 188561, 57490, 188563, 57492, 188565, 57494, 188567, 57496, 188569, 57498, 188571, 57500, 188573, 57502, 188575, 57504, 188577, 57506, 188579, 57508, 188581, 57510, 188583, 57513, 57515, 57517, 57519, 57521, 57523, 57525, 57527, 57529, 57531, 57533, 57535, 188609, 57539, 188613, 57542, 188615, 57544, 188617, 57546, 188619, 57548, 188621, 57550, 188623, 57552, 188625, 57554, 188627, 57556, 188629, 57558, 188631, 57560, 188633, 57562, 188635, 57564, 188637, 57566, 188639, 57569, 57571, 188645, 57575, 57577, 57579, 57581, 57583, 188657, 57587, 57589, 57591, 57593, 57595, 188669, 57599, 57601, 57603, 57605, 57607, 188681, 188683, 57613, 57615, 57617, 57619, 57621, 57623, 57625, 188258, 188260, 188262, 188264, 188266, 57208, 188292, 57222, 57224, 188298, 188302, 188304, 188306, 188308, 188310, 188312, 188314, 188316, 188318, 188320, 188322, 188324, 57254, 188328, 188330, 188332, 188334, 188342, 188348, 188384, 188386, 188388, 188390, 188392, 188394, 188404, 188406, 188408, 57338, 57340) ORDER BY "stock_move"."date_expected" DESC,"stock_move"."id"

2016-07-04 00:19:41,799 805 DEBUG PROD openerp.sql_db: query: UPDATE "stock_move" SET "picking_type_code"='internal',"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (8379)

2016-07-04 00:19:41,800 805 DEBUG PROD openerp.sql_db: query: select id from wkf_instance where res_id=8379 and res_type='stock.move' and state='active'

2016-07-04 00:19:41,814 805 DEBUG PROD openerp.sql_db: query: UPDATE "stock_move" SET "picking_type_code"='internal',"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (270524)

2016-07-04 00:19:41,815 805 DEBUG PROD openerp.sql_db: query: select id from wkf_instance where res_id=270524 and res_type='stock.move' and state='active'

**Comment by pedrobaeza** [comment]
I don't see in that trace anything involved with the module. Are you talking about performance in a daily basis, at module install moment, or when?

**Comment by pedrobaeza** [comment]
No answer for a while, so I close.
