### ISSUE TITLE
Strange behavior when edit the ordered qty to be less than the available qty.

### ISSUE THREAD

**Issue by bisolutions-git** [OCA/stock-logistics-warehouse#1765]
## Module
Stock MTS+MTO Rule

## Describe the bug
When generating a quotation, if the ordered quantity is 3 but the available quantity is only 2 in Odoo, the system will create a purchase order for 1 quantity. This is the intended outcome. However, if we modify the ordered quantity to 1, Odoo will generate a return order for 2 quantities and put it on hold for further processing with waiting another operation status. I am unsure why this occurs, but it would be more appropriate to directly edit the demand to 1 quantity instead of creating a return order.

## To Reproduce
**Affected versions**:
V.15
1. 
2.
3.

**Expected behavior**
it's better to edit the demand to be 1 qty directly not creating a return order.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by rousseldenis** [comment]
@alan196 @PierrickBrun @florian-dacosta
