### ISSUE TITLE
[feature request] stock_mts_mto_rule to create manufacturing order

### ISSUE THREAD

**Issue by roboticsound** [OCA/stock-logistics-warehouse#178]
Hi,
I would like something very similar to this feature, however as the pieces are manufactured in house i would like a manufacturing order to be created instead of a purchase order. The workflow would check whether parts are in stock first and then create a manufacturing order for any parts that need to be created. As far as I can tell the module does not currently do this. I may be willing to take this on but could someone give me any advice and point me in the right direction?
Thanks,

**Comment by pedrobaeza** [comment]
Closing as this is only a request, but no PR exercising it.
