### ISSUE TITLE
[V14] stock_location_position,  "development_status": "Alpha", while V16 already stable, any concern?

### ISSUE THREAD

**Issue by bunhin** [OCA/stock-logistics-warehouse#1856]
It is a question only. It is have any concern on V14 the module is still in "Alpha" while V16 already stable?

**Comment by rousseldenis** [comment]
Hi @bunhin, indeed, some modules could have different development status between main branches as that reflects different stages of module maturity. Here, the module could have been started in v14 and enhanced in v16. Some feature could miss in the earlier version for instance.
