### ISSUE TITLE
System does not prevent the to move items to location

### ISSUE THREAD

**Issue by BT-srieskamp** [OCA/stock-logistics-warehouse#1866]
module: stock_location_product_restriction
version: 16.0

**Steps to reproduce**
- Create a new location or use one that has no products
- Go to the location and choose "only items of the same product..."
- Receive a product on that location.
- Receive another product on that location

**Current behavior**
- The system accepts the second product on that location.
- It only shows the violation.
**Expected behavior**
- Whether I am in the Barcode App or in the backend view, I expect that I cannot either choose that location or I cannot validate with a message that tells me that the location already has products. The description says so: "Once a location is configured to only contains items of the same product, **the system will prevent you to move items of any others products into a location** that already contains product items.

**Comment by rousseldenis** [comment]
@BT-skettler Thanks reporting this. I will try to improve testing as normally this raises an Exception, so products should not be moved in the destination location.
