### ISSUE TITLE
[16] stock_move_location - Changes on readme

### ISSUE THREAD

**Issue by Gelojr** [OCA/stock-logistics-warehouse#1882]
**Is your feature request related to a problem?**
I add some changes to improve the readme on V16
**Describe the solution you'd like**
Add information to the readme
**Describe alternatives you've considered**

- Delete this part. The button does not appear- Doesn't it?

> If you go to the Inventory Dashboard you can see the button "Move from location" in each of the picking types (only applicable to internal transfers). Press it and you will be directed to the wizard.

I could not find the "Move from location" button.

https://www.loom.com/share/d07016f3921d4740afbbb2e0234dbc50?sid=dfc21526-c6c6-4820-99d9-ee90cc37a6d5

- Add bold text

> On a draft picking, add a button to fill with moves lines for all products in the source destination. This allows to create a picking to move all the content of a location.
**The Origin Location must have stock**
**The Destination Location has to be a final location**
If some quants are not available (i.e. reserved) the picking will be in partially available state and reserved moves won't be listed in the operations. Use barcode interface to scan a location and create an empty picking. Then use the fill with stock button.

@yajo can you make a PR to change it?

@moduon MT-3609

**Comment by yostashiro** [comment]
@Gelojr I think it's meant to be 'Move on Hand' button which can be enabled with picking type configuration.

![image](https://github.com/OCA/stock-logistics-warehouse/assets/7766939/f20849c6-ff0b-4821-a38b-973835c09f7e)
![image](https://github.com/OCA/stock-logistics-warehouse/assets/7766939/ca63f439-6aef-43bd-ae8d-6bd31dfd5b84)

But indeed, the readme can be improved by perhaps adding a CONFIGURE file with this description.

**Comment by Gelojr** [comment]
@yostashiro Thank you for your reply. As you say, I would add this part. I would change this in the post https://github.com/OCA/stock-logistics-warehouse/issues/1882#issue-1981967728

> Delete this part. The button does not appear- Doesn't it?
> If you go to the Inventory Dashboard you can see the button "Move from location" in each of the picking types (only applicable to internal transfers). Press it and you will be directed to the wizard.
> I could not find the "Move from location" button.

by

> If you go to the Inventory Dashboard you can see the button "Move from location" in each of the picking types (only applicable to internal transfers). Press it and you will be directed to the wizard.
![281220235-ca63f439-6aef-43bd-ae8d-6bd31dfd5b84](https://github.com/OCA/stock-logistics-warehouse/assets/147538094/208ea309-0bad-43e7-bd6f-8384520afe00)
> **To enable this option, check "Show Move On Hand Stock" in the Picking Type configuration.**
> ![281220193-f20849c6-ff0b-4821-a38b-973835c09f7e](https://github.com/OCA/stock-logistics-warehouse/assets/147538094/45fa4bde-36be-4ba1-8d54-8e707b89459e)
>

**Comment by rafaelbn** [comment]
Solved in https://github.com/OCA/stock-logistics-warehouse/pull/1892
