### ISSUE TITLE
stock_mts_mto_rule - How to use with products that have a Bom type =set

### ISSUE THREAD

**Issue by sdalexander** [OCA/stock-logistics-warehouse#218]
Hi Guys
I have installed this module and it works well for most product set up's , however I am trying now to get it working with products that have a BOM with type = set .
ie. product A has a Set BOM to pull qty 2 of product B,which has a Normal BOM . Stock can be held against product B, No stock is held against Product A.
so If I have an sale order for 10 of product A, with 5 in stock of product B.
I expect an MO for 15 of product B  to get the 20 needed to satisfy the sale order 
I have tried a number of combinations of route setting against the products.
but I always end up with MO for the Full order qty of 20 as if it is using MTO linked back to the sale order.

will this module work with Bom type set?

Any ideas of a route/procurement rules that will achieve this?

thanks in advance

Steve

**Comment by florian-dacosta** [comment]
Hello,
I am not sure, I think it your case can't work for one step delivery, but it may work for a 2 step delivery...
Anyway, it would probably be a good improvement to make for the module

**Comment by alyngsoe** [comment]
Hi sdalexander
Did you find a solution for your issues with MTS module for BOM products ? We have the same issue/needs.

**Comment by rousseldenis** [comment]
@sdalexander @alyngsoe Fixed ?

**Comment by alyngsoe** [comment]
@rousseldenis No, this was an issue for a version8. The customer ended up with creating re-ordering rules instead to push MO's. So we did not try the fix.
