### ISSUE TITLE
RFC: Cycle Count in Odoo

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/stock-logistics-warehouse#237]
# Introduction

The purpose of this RFC is to define the design for a Cycle Count tool in Odoo.

Versions impacted: 8.0 and 9.0.

In order to design, we propose to use as reference the following article: http://www.tompkinsinc.com/wp-content/uploads/2012/06/WP-19_Cycle_Counting.pdf

Comments on functional requirements
Introduce here comments on the previous article.

# Design in Odoo

## Location(stock.location)
* Acceptable Inventory Quantity Variance Threshold (what if this location contains multiple products? - perhaps it is a unitless field - could be mixing apples and oranges here)
* Acceptable Inventory Quantity Variance Rate Threshold
* Acceptable Inventory Cost Variance Threshold.
* Acceptable Inventory Cost Variance Rate Threshold.
Note: perhaps using variance rate is more useful.

## Warehouse (stock.warehouse)
* Applicable rules (cycle.count.rule)

## Cycle Count Rule (cycle.count.rule)
This model will constitute the basis from which other modules will build upon, to create specific rules. Will be an abstract model.

### Data model
Name
Warehouses (where it is applicable)
### Method ‘compute’:
* Input. 
Warehouse
* Output.  Produce a list of
** Required Date
** Location

## Cycle Count Rule - minimum by location
This rule will allow to identify the next required cycle count for locations, considering a minimum number of times a SKU and/or location must be counted in a year to meet the criteria set by accountants.
## Cycle Count Rule - Turnover inventory value
This rule will allow to identify the next required cycle count for locations, considering a threshold of turnover inventory value defined for a product and/or location. When the total value of items moved in/out from the date of last count of a product and location exceeds a threshold, this product/location should be counted again.

## Cycle Count Rule - Moved quantity
This rule will allow to identify the next required cycle count for locations, considering a threshold of moved quantity defined for a location. When the total volume of items moved in/out from the date of last count of a product and location exceeds a threshold, this product/location should be counted again.

## Cycle Count Rule - Accuracy level
This rule will allow to identify the next required cycle count for locations, considering the accuracy level  defined on that location. If the past accuracy is low, the items should be counted more frequently.

The accuracy level, could be:
* Cost variance rate threshold
* Quantity variance rate threshold
* Cost variance threshold
* Quantity variance threshold

Then the `compute` method of this rule is run, all the locations should be selected

**TODO**: How do we measure and record accuracy on a location?

## Cycle Count Queue generator
Identifies the rules applicable to the warehouse
Calls the method ‘compute’ for every rule
Obtains the earliest planned cycle count date (or for the defined cycle count planning horizon) for each location, based on the results of evaluating all the rules.
If there’s no Cycle Count already scheduled, it Creates Cycle Counts with the defined required date and location.
If there is a Cycle count pending, the new Cycle counts comes after the pending ones.

## Cycle Count
Constitutes the basis for the Cycle Count queue. Cycle Counters should count items in inventory according to the planned cycle counts.
### Data model
* Location
* Required Date
* Assigned to (user)
* Status (Planned, Execution, Cancelled, Done)
* Cycle count rule (that it originated from), so that people know why was this cycle count proposed.

When a cycle count is started, an Inventory Adjustment is created of type ‘Scheduled Cycle Count’. The user will record the actual count in that Inventory Adjustment.
When the adjustment is validated the cycle count is Done.

### Data model
* Quantity Variance. Sum of the quantity for all inventory adjustment lines.(computed, stored field)
* Quantity Variance Rate. Quantity Variance for all items / Total Quantity for all items on that location. (computed, stored field)
* Cost Variance. Sum of the actual inventory variance for all inventory adjustment lines. (computed, stored field)
* Cost Variance Rate (%). Cost Variance for all items / Total Cost for all items on that location. (computed, stored field)

### Data model
* Quantity Variance. Difference between the theoretical quantity and the actual quantity for all items of the inventory adjustment.  (computed, stored field)
* Cost Variance. Difference between theoretical and actual quantity, valued at the cost of the quants. (computed, stored field)
* Cost Variance Rate (%). Cost Variance / Total Cost for that item and location. (computed, stored field)

## Stock Move (stock.move)
When as a result of a stock move the quantity on hand for that product in the source location is 0 a new Inventory Adjustment of type ‘Zero Confirmation’ should be created for that source location and product.

## Slot Verification Request (stock.slot.verification.request)
Are triggered when either a normal warehouse operation or a cycle counting operation uncovers a count discrepancy within a slot, and the discrepancy is greater than the pre-defined acceptable variance threshold.
### Data model
* Inventory Adjustment (where the discrepancy was identified)
* Status
* Assigned to

## SKU Verification (stock.sku.verification.request)
Occur when the slot verification confirms that a count discrepancy exists and it is greater than the pre-defined acceptable variance threshold. The SKU verification process should be set up to logically sequence the slots being verified so that the slots with the highest probability of having the off setting inventory discrepancy are visited first.
**WIP**
Perhaps in this state we should help by providing to the user information of what are the locations that this location feeds to, based on the routes?

## Inventory Adjustment (stock.inventory.adjustment)
Should add a new field ‘Count Type’ with values:
* Scheduled Cycle Count
* Zero Confirmation
Should be exhaustive (all products inside the location). See module 'stock_inventory_exhaustive' in https://github.com/OCA/stock-logistics-warehouse/pull/155

When an inventory adjustment is in progress, it is not allows to move stock in or out of that location. See https://github.com/OCA/stock-logistics-warehouse/tree/8.0/stock_inventory_lockdown

When a discrepancy occurs for type ‘Scheduled Cycle Count’ and the variance is above the threshold, it should trigger a new ‘Slot Verification’.

When a discrepancy occurs for type ‘Zero Confirmation’ it should trigger a new ‘Slot Verification’ (regardless of the variance).
When an Inventory Adjustment is in progress no moves are allowed in/out of this location. See module: https://github.com/numerigraphe/stock-logistics-warehouse/tree/8.0-migrate-advanced-inventory2

### Security groups:
* **Cycle Counter**: Can create Inventory Adjustments. Can post Inventory Adjustments, provided that the difference between the physical and system counts lies within the Acceptable Variance defined for this product.
* **Warehouse Operator**: Can only  create Inventory Adjustments of type ‘Zero Confirmation’. Can post Inventory Adjustments of this type, as long as the quantity in the system and the real quantity matches and it is 0. Is allowed to perform the usual stock transfers.
* **Inventory Control Specialist**: Is allowed to conduct Slot and SKU Verifications. Allowed to create any Inventory Adjustment, but not post.
* **Inventory Control Manager**: Is allowed to approve and post any inventory adjustments.

# Outstanding Issues

* In the reference document the Inventory Control Manager is the only one who can release into accounting the inventory adjustments. In Odoo just by posting the stock moves will create the accounting entries. We understand that the other roles should be able to post stock moves. 

* When you create an inventory adjustment for a parent location (e.g. WH/Stock) Odoo will propose the current on hand inventory of all child locations (e.g. stock in WH/Stock and WH/Stock/Shelf 1). But if we are to conduct cycle counts, each location should be counted only by means of the stock in that location, and not the children. In that case, we would expect that WH/Stock and WH/Stock/Shelf 1 would be counted separately, provided that WH/Stock and WH/Stock/Shelf 1 both have quantities on hand in their respective locations. In that case https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L2809 would need to be changed to include only the location that is being inventoried, not the children.

# Bibliography

[1] http://www.tompkinsinc.com/wp-content/uploads/2012/06/WP-19_Cycle_Counting.pdf
[2] http://www.strategosinc.com/downloads/cycle_count_articles.pdf

**Comment by JordiBForgeFlow** [comment]
cc @aheficent @jceficent

**Comment by LoisRForgeFlow** [comment]
*'stock.inventory.adjustment'* doesn't exist, did you mean *'stock.inventory'*? or is a new model called like that needed?

**Comment by JordiBForgeFlow** [comment]
@lreficent  stock.inventory

**Comment by LoisRForgeFlow** [comment]
In order to define the accuracy level calculation rule we will need the user to define some fields:
* Expected Inventory Accuracy
* Precision Required (or Tolerance with the result)
* Number of Counts needed (NC): to verify the estimation, this is calculated with the two fields above. An important point is that these counts have to be selected randomly.

Then, after performing those counts we can obtain the actual Inventory Accuracy (IA) as a division between the number of errors found in the counts (NE) and the NC:
IA = NE/NC

As a extension we can also add:
* The capability to recalculate the tolerance if the difference between EIA and IA is big. As well as defining some possible action after this.
* A control chart with all the records of the IA that have been calculated. With this, we can define a Lower Control Limit to track possible downward trends and take actions to fix them.

**Comment by JordiBForgeFlow** [comment]
Closing the issue, as the features have now been implemented in:

https://github.com/OCA/stock-logistics-warehouse/tree/9.0/stock_cycle_count
https://github.com/OCA/stock-logistics-warehouse/tree/9.0/stock_inventory_discrepancy
https://github.com/OCA/stock-logistics-warehouse/tree/9.0/stock_inventory_verification_request

**Comment by normalperson16** [comment]
File "/opt/odoo/addons/stock_account/models/stock_move.py", line 254, in _action_done
    for move in res - self:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'stock.move'
