### ISSUE TITLE
Rounding precision

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/stock-logistics-warehouse#242]
By default the rounding precision of the unit of measure "Units" is 0.001, which can lead to errors when rounding. For example here: https://github.com/OCA/stock-logistics-warehouse/pull/234 Would be good to create a PR to fix this?

![image](https://cloud.githubusercontent.com/assets/19620251/22143442/5973f3e6-defa-11e6-98eb-48cd5f8032a3.png)

**Comment by andhit-r** [comment]
I always edit it on every implementation. Sure you can always create a PR to Odoo for it. But then you have to create one hell of migration script to adjust stock calculation.

**Comment by JordiBForgeFlow** [comment]
Yes, this would not apply to OCA. You can close the issue.
