### ISSUE TITLE
New module to show in pickings a Smartbutton with sale order it comes from

### ISSUE THREAD

**Issue by rafaelbn** [OCA/stock-logistics-warehouse#254]
Hi,

The purpose is to be able to navigate to the sale order from the picking

I thought it would be here in OCA but not yet

Anyone have something like this please?

Thanks

cc @sergio-teruel

**Comment by sergio-teruel** [comment]
Hi @rafaelbn this addon is in https://github.com/OCA/stock-logistics-workflow/tree/9.0/stock_picking_sale_order_link
