### ISSUE TITLE
[v10] - stock_mts_mto_rule - traceback when renaming warehouse code (without renaming warehouse name)

### ISSUE THREAD

**Issue by bistaray** [OCA/stock-logistics-warehouse#271]
File "/odoo-dev/custom/collaboration-solutions-inc/stock_mts_mto_rule/model/warehouse.py", line 137, in _update_name_and_code
    warehouse.name, name, 1)
TypeError: coercing to Unicode: need string or buffer, NoneType found

In this case **name** is False.

Offending line of code is https://github.com/OCA/stock-logistics-warehouse/blob/10.0/stock_mts_mto_rule/model/warehouse.py#L134

I changed

if warehouse.mts_mto_rule_id:

to:

if warehouse.mts_mto_rule_id and name:

and so far it works

**Comment by pedrobaeza** [comment]
I have fixed it directly as pretty obvious, but in another way from what you propose in https://github.com/OCA/stock-logistics-warehouse/commit/be6745ae8deda174981c85898791f6b16b1a8c76.
