### ISSUE TITLE
[RFC] Add Chatter to stock.inventory

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/stock-logistics-warehouse#288]
We have identified that it is usual for people to log some insights around inventory adjustments. We also identify that changes key attributes of the inventory adjustment should be logged. E.g. when the status of the adjustment changes.

We plan to introduce a module 'stock_inventory_chatter', that just adds this capability.

**Comment by JordiBForgeFlow** [comment]
cc @mreficent @lreficent

**Comment by JordiBForgeFlow** [comment]
@mreficent can you work on this one?

**Comment by rousseldenis** [comment]
@jbeficent I think this is solved.
