### ISSUE TITLE
MTO+MTS rule for manufactured parts

### ISSUE THREAD

**Issue by ccandito** [OCA/stock-logistics-warehouse#289]
Dear All,
we'd use this rule for manufactured parts.
it seems it is not possible because from a SO no MO has been created for a product having set up this rule.
Regards
claudio candito

**Comment by eLBati** [comment]
@ccandito which module are you referring to?
What are the steps to produce the problem?

**Comment by JordiBForgeFlow** [comment]
@ccandito See https://github.com/OCA/manufacture/pull/191

**Comment by rousseldenis** [comment]
@ccandito Ok for you?

**Comment by ccandito** [comment]
yes, please
I'm closing it
I've tested it again 
Thanks a lot
claudio
