### ISSUE TITLE
[8.0]stock_inventory_hierarchical missing exception module

### ISSUE THREAD

**Issue by flotho** [OCA/stock-logistics-warehouse#298]
Hi,

I've recently updated my repo and I have this issue now :
``` 
  from . import inventory_hierarchical_location
  File "/home/florent/DEV/Lib_Odoo/OCA-warehouse/stock_inventory_hierarchical_location/inventory_hierarchical_location.py", line 24, in <module>
    from openerp.addons.stock_inventory_hierarchical.exceptions import HierarchicalInventoryException
ImportError: No module named exceptions
```
Two reflection from my side  :
* Is it necessary to have auto_install : https://github.com/OCA/stock-logistics-warehouse/blob/8.0/stock_inventory_hierarchical_location/__openerp__.py#L49
* Is it normal that no exception seems to appear other hierarchical modules?

regards

**Comment by rousseldenis** [comment]
@flotho See https://github.com/OCA/stock-logistics-warehouse/pull/155. It has been moved.

I close this. Please feel free to make another issue if not resolved.
