### ISSUE TITLE
Singleton Error

### ISSUE THREAD

**Issue by vst** [OCA/stock-logistics-warehouse#31]
I have a self-referential `one2many` relationship on my `product.product` model.

I received a weird "Expected singleton" exception when showing the product page (form) and somehow managed to solve it by changing `@api.multi` to `@api.one` on https://github.com/OCA/stock-logistics-warehouse/blob/8.0/stock_reserve/model/product.py#L63. This probably applies to `product.template` as well.

What do you say?

PS: Still find it weird as the `stock_reserve`'s button should apply to the single `product.product` instance in the domain, anyway.

**Comment by pedrobaeza** [comment]
I don't see any problem in current code, so the problem should be in your side. Closing this.
