### ISSUE TITLE
module stock_put_away_product

### ISSUE THREAD

**Issue by bealdav** [OCA/stock-logistics-warehouse#315]
## what
module stock_put_away_product v8 to v9

## what's wrong
In the readme we can read:

> A recommended set-up is to create a separate putaway strategy for each warehouse. This will ensure that the same product will be placed in the appropriate location in each warehouse it is received.

Ok then in my company I should only see putaway rule relative to my company. 

However not easy to define security rules without company_id field

## What I propose
Recommandation implied to have one putaway by warehouse, then we may add a computed company_id based on the warehouse company_id. Then I can define a security rule based on it

On my side I just need 1 putaway_strategy_id for all locations of the warehouse. I don't know if it's generic. Are you ok with that ?

cc @jbeficent @benoitguillot @tafaRU @carlosdauden @rousseldenis

**Comment by rousseldenis** [comment]
@bealdav In fact, you can have several strategies for the same warehouse.

For example in receptions, you have the Quality location and several sublocations, and in Stock location you have several sublocations too.

You can define a strategy on Quality, and another one on Stock with different rules on product level or on product category level.

At the security rules level, indeed there is a brick missing.
I'm not an expert on that domain, but an approach could be adding a security rule on the fixed_location_id in stock.product.putaway.strategy model.

But there comes the problem if picking assignation is done with sudo...

**Comment by bealdav** [comment]
Thanks for the answer.

**Comment by rousseldenis** [comment]
@bealdav Closing?
