### ISSUE TITLE
MTS+MTO Rule doesn't generate the necessary PO from a Manufacturing order

### ISSUE THREAD

**Issue by BeAntares** [OCA/stock-logistics-warehouse#323]
When a Sales Order triggers a Manufacturing Order using the MTS+MTO rule and there are some products from the Bill of Materials that don't meet the required quantities, the rule doesn't create the Purchase Orders as it works using the 'Make to Order' rule.

**Comment by LoisRForgeFlow** [comment]
Hi @BeAntares 

Have a look to the module proposed in this PR: https://github.com/OCA/manufacture/pull/191. I think it may be what you need.

**Comment by BeAntares** [comment]
Thanks @lreficent. It think it could work. Is it adapted to v10?

**Comment by LoisRForgeFlow** [comment]
@BeAntares yes, there is also an open PR in v10: https://github.com/OCA/manufacture/pull/216

**Comment by BeAntares** [comment]
Gracias @lreficent, I'll check it out.
