### ISSUE TITLE
Reservation takes long time, commenting some lines in core module make it faster. Is it safe?

### ISSUE THREAD

**Issue by BetaUliansyah** [OCA/stock-logistics-warehouse#338]
Im using #239 and #274 in v10. But when doing reservation, it takes up to 3 minutes. 

A friend suggested to comment these lines of stock_move.py in stock module (line number 616-618 and 644-645):

`quants = Quant.quants_get_preferred_domain(qty, move, ops=ops, domain=domain, preferred_domain_list=[])
Quant.quants_reserve(quants, move, record)`  

The reservation time was not so long anymore after that, and the products are reserved well. There are 2 questions in my mind:
1. Is it safe?
2. What are those lines actually do?

**Comment by rousseldenis** [comment]
@BetaUliansyah It's not recommended to do so.

Maybe, can you add a llittle description of your issue and environment? How many product lines do you have, do you have other OCA modules installed, ... ?
