### ISSUE TITLE
Odoo V10: couldn't sell a product based on a phantom-type BoM

### ISSUE THREAD

**Issue by cyp-opennet** [OCA/stock-logistics-warehouse#344]
Hi

I have a product, with a BoM defined as type 'phantom'.
When I confirm the sale, Odoo in its normal process explodes the stock move into the BoM's components, and then deletes the original stock move.
With the module 'stock_mts_mto_rule' activated, the system raises this error: "Record does not exist or has been deleted."

Sold product's only route: "Buy"
Component's route: "Manufacture"
One warehouse, very classic stock locations setup.

Thanks for any help.

**Comment by rousseldenis** [comment]
@cyp-opennet Could you please test it on runbot and give us stack trace if it raises?

I've just tested it and no error. Maybe you configured something different?

**Comment by rousseldenis** [comment]
No answer. Closing
