### ISSUE TITLE
[stock_mts_mto_rule] P.O not auto-generated for zero(0) stock products.

### ISSUE THREAD

**Issue by blutecsolutions** [OCA/stock-logistics-warehouse#345]
Hello, 

Thanks alot for all efforts put in the modules

Concerning this module: https://www.odoo.com/apps/modules/10.0/stock_mts_mto_rule/
I've tried it on the OCA runbot: 
When product has MTO + MTS route set + BUY route,
- the Purchase Order is not auto-generated for products with zero(0) stock -- 
- but products with stock more than 0 can be transferred successfully by Delivery Order.

What am i doing wrong.?

Thanks and your help is much appreciated.

**Comment by blutecsolutions** [comment]
EDIT: I'm not using the Manufacting.Order, 
- Delivery Order is created via the Sales.Order

**Comment by blutecsolutions** [comment]
Ok i found out that the MTO + MTS Route is not configured by default after installing the module, i will record a short video tutorial and we can add it to the module description.
Thanks ,

**Comment by rousseldenis** [comment]
@blu777 So, solved ?
