### ISSUE TITLE
[10.0] Transifles translation empty

### ISSUE THREAD

**Issue by FrancoTampieri** [OCA/stock-logistics-warehouse#357]
Hi @pedrobaeza! I have noticed that transiflex that Transiflex does not present translations of some OCA modules, including specifically those of this project. I would like to contribute translating some of these modules into Italian, but at the moment I can not do without making a fork of the project, manually using poedit and making a merge proposal.

I attach a couple of screenshots of the transflex screen

![screenshot 2017-11-26 05 05 49](https://user-images.githubusercontent.com/4396444/33237065-cd59e2f4-d268-11e7-885d-c5008945407b.png)

![screenshot 2017-11-26 05 15 44](https://user-images.githubusercontent.com/4396444/33237069-eb243faa-d268-11e7-8d24-f6796939b61a.png)

Best regards

Franco

**Comment by pedrobaeza** [comment]
Hi @drdran, I have fixed this in https://github.com/OCA/maintainer-quality-tools/commit/0a3591eb34452f84e83253d36e1b64b880dd0616, so check now Transifex
