### ISSUE TITLE
Module name: technical vs functional name

### ISSUE THREAD

**Issue by bealdav** [OCA/stock-logistics-warehouse#36]
As you can see here https://github.com/OCA/stock-logistics-warehouse/blob/7.0/stock_available_mrp/__openerp__.py 
the module is:
technical: stock_available_mrp
functional: Consider the production potential is available to promise
Why those names are so different ?
Why don't use summarize key as 'Consider the production potential is available to promise' 
and 'Stock Available MRP' as fucntional name ?

**Comment by yvaucher** [comment]
I think the phrase can go under `summary` key

**Comment by pedrobaeza** [comment]
You can propose a PR changing it, David.
