### ISSUE TITLE
[pylint] stock_inventory_exclude_sublocation: pylint error

### ISSUE THREAD

**Issue by rousseldenis** [OCA/stock-logistics-warehouse#370]
@mreficent There is a pylint error.

https://github.com/OCA/stock-logistics-warehouse/blob/6a0d337bafee7103f9ae7209b391eb76243c4ee6/stock_inventory_exclude_sublocation/models/stock_inventory.py#L53

Use read_group() function instead.

**Comment by MiquelRForgeFlow** [comment]
Blame Odoo https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_inventory.py#L259

cc: @lreficent

**Comment by rousseldenis** [comment]
@mreficent :innocent: We could do better :smile:

**Comment by rousseldenis** [comment]
Solved by https://github.com/OCA/stock-logistics-warehouse/commit/ccef294065f9dac17947dc5db8b99ecdc09a7d8c
