### ISSUE TITLE
V10 Manual Quant Assignment - Functionality Issues

### ISSUE THREAD

**Issue by conroyke56** [OCA/stock-logistics-warehouse#372]
I have a couple of issues I have noticed whilst testing this module for our application. This may be me going through the process wrong.

Items in stock
create transfer out
enter product and QTY
Mark as to do
reserve stock

quants automatically assigned

new quants are automatically created.
if we adjust the selected quants (for example wrong lot was selected) the newly created quants remain.

Is this as expected?

Am I doing something wrong by reserving the stock?
I cant seem to get the manual quant option to appear without reserving stock.

would love some advice, sorry for my poor communication.
Cheers,

**Comment by fanha99** [comment]
hi @conroyke56:
by default, the odoo is not merge the quants when you "unreserved".
this module is just call the "unreserved" before assign the other.

to merge the quants, you can install https://github.com/OCA/stock-logistics-warehouse/tree/10.0/stock_quant_merge. 
that module will auto merge when you press unreserved on the delivery order.

it is better to unreserved before manual assign the other.
