### ISSUE TITLE
[10.0] manual quant assignment stock traceability

### ISSUE THREAD

**Issue by conroyke56** [OCA/stock-logistics-warehouse#373]
Anyone have this same issue when using quant manual assignment:
Reserving stock with manual assign installed creates new quant for the same lot number etc. 
when checking traceability, because new quant is created, you cannot trace movements against the quants.

**Comment by pedrobaeza** [comment]
That's not true. It doesn't create new quant, but split previous one if you reserved some partial quantity, but quant history/traceability is preserved.

**Comment by conroyke56** [comment]
But it doesn’t reverse if you change the selected quant before validation. Or if you later cancel the transfer. 
The split remains. 

Also, is it true that you have to reserve the stock before manual quant option appears?

**Comment by pedrobaeza** [comment]
Yeah, but that's not a problem of the module, but Odoo design. In v11 it has been changed.

**Comment by conroyke56** [comment]
for the reserve stock? yes.
But the quant split still exists.
So every order I create, a split is created, but if I change the automatically selected quant, the split does not reverse.
Is this expected?

**Comment by pedrobaeza** [comment]
Yes
