### ISSUE TITLE
[stock_available][10.0] Module doesn't work

### ISSUE THREAD

**Issue by edser-pcg** [OCA/stock-logistics-warehouse#383]
After installing the stock_available module it shows two new buttons within the product view (Available and Promise), however they don't show any real information.

The itention of installing this module was to have the available quantities of products that can be manufactured because all the BoM components currently have stock.

**Comment by rousseldenis** [comment]
@edsersolis This module is the base for other ones that can fit your requirements (all 'stock_available_...' modules). I think about stock_available_immediately. Is that ok for you ?

**Comment by rousseldenis** [comment]
Closing this old one
