### ISSUE TITLE
Is anyone working on stock_mts_mto_rule for Version 11?

### ISSUE THREAD

**Issue by RCIclark** [OCA/stock-logistics-warehouse#390]
Greetings,

I'm new to Odoo and am looking for module stock_mts_mto_rule for Version 11.  Is anyone working on this at this time? I know that v11 is a different setup than v10, but the basic need is still there.  I am looking to make to order but need to pull from stock first.  Any feedback is appreciated.  I am willing to help pay for the update.  Thanks!

**Comment by pedrobaeza** [comment]
No one has said anything about this. There's a migration for coordinating migration efforts: #343

**Comment by RCIclark** [comment]
okay, thanks.  Sorry, I'm new to this.
