### ISSUE TITLE
stock_orderpoint_purchase_link

### ISSUE THREAD

**Issue by max3903** [OCA/stock-logistics-warehouse#430]
https://github.com/Eficent/ddmrp/pull/60

# Stock Order Point Purchase Link

This module allows to link the stock order point and the generated PO line.

# Usage

* Create a MTS purchased product with a reordering rule
* Run the scheduler
* Check the new PO line is linked to the reordering rule

**Comment by JordiBForgeFlow** [comment]
Good! I'll check asap

**Comment by max3903** [comment]
@bodedra should have something for us tomorrow. Meanwhile @jbeficent can you help us here:
https://github.com/Eficent/stock-rma/pull/30 and there:
https://github.com/Eficent/stock-rma/pull/31

**Comment by bodedra** [comment]
We are ready to go.

CC @max3903 @jbeficent

**Comment by max3903** [comment]
Implemented in #435
