### ISSUE TITLE
stock_orderpoint_manual_procurement Procure Recommendation sortable

### ISSUE THREAD

**Issue by eversatis** [OCA/stock-logistics-warehouse#439]
Can you make the Procure Recommendation quantities sortable on list view? It is also not filterable like filtering quantity over 0. If I have many orderpoints, I will not know which ones trigged the procurement without quantity 0. If this is sortable, I can quickly click it as descending sort and select the ones need procurement. My Run Scheduler do not quite work well, so I would like to use this module to generate RFQ from time to time. Thank you!

**Comment by rousseldenis** [comment]
@jbeficent @lreficent

**Comment by LoisRForgeFlow** [comment]
That's what we actually did for ddmrp, we made the field stored (hence sortable and searchable). However, I'm not sure this is what the default module should do, we'd like to keep it simple and changing that now will likely impact many instances already using this module. You can propose a extension (new module depending on stock_orderpoint_manual_procurement) that makes the recommended qty stored if you want. This way, everyone can choose which option do they want.
