### ISSUE TITLE
stock_inventory_revaluation - version 10.0

### ISSUE THREAD

**Issue by ccandito** [OCA/stock-logistics-warehouse#441]
Deat All,
We've created a new product code with perpetual inventory valuation method and standard price as costing method.
we haven't been able to use the "Stock Inventory Revaluation" module for the following reasons:
1) we've tried to update price from product master data or inventory revaluation and the following error occurred: Cannot do an inventory value change if the quantity available for product XXX-001 is 0 or negative
2) so we've tried to update the quantity from master data product or inventory adjustment receiving the error: The found valuation amount for product XXX-001 is zero. Which means there is probably a configuration error. Check the costing method and the standard price

thanks in advance
Claudio

**Comment by farazbdm** [comment]
@pedrobaeza 
is it possible to get a hint on this same issue.
stuck in abyss, when its AVCO enabled, and cost was 0, quantity was 0.

Not able to update either of them.

**Comment by pedrobaeza** [comment]
Sorry, I'm not a user of this module.

**Comment by farazbdm** [comment]
can you please recommend someone, will be highly thankful

**Comment by farazbdm** [comment]
@JordiBForgeFlow @sergio-teruel 
can you please help
