### ISSUE TITLE
Stock Inventory Verification Request Install Error

### ISSUE THREAD

**Issue by digitalliuzg** [OCA/stock-logistics-warehouse#455]
File "I:\OCB\greenodoo10-OCB\odoo10\odoo\models.py", line 1081, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "constraint \u68c0\u67e5\u9519\u8bef

\u5143\u7d20 '<xpath expr="//field[@name='line_ids']/tree/field[@name='discrepancy_threshold']">' \u5728\u7236\u89c6\u56fe\u4e2d\u6ca1\u6709\u627e\u5230

\u9519\u8bef\u7684\u4e0a\u4e0b\u6587:
\u89c6\u56fe `Inventory form view - SVR extension`
[view_id: 1080, xml_id: n/a, model: stock.inventory, parent_id: 371]
None" while parsing file:/i:/ocb/greenodoo10-ocb/ocaaddons/stock_inventory_verification_request/views/stock_inventory_view.xml:7, near
<record id="view_inventory_form" model="ir.ui.view">
        <field name="name">Inventory form view - SVR extension</field>
        <field name="model">stock.inventory</field>
        <field name="inherit_id" ref="stock.view_inventory_form"/>
        <field name="arch" type="xml">
            <data><xpath expr="//button[@name='action_done']" position="after">
                <button name="action_request_verification" string="Request Verification" type="object" class="oe_highlight" attrs="{'invisible': ['|',('state', '!=', 'pending'),('requested_verification', '=', True)]}" groups="stock.group_stock_user"/>
            </xpath>
            <field name="name" position="after">
                <field name="requested_verification" invisible="1"/>
            </field>
            <notebook position="inside">
                <page string="Slot Verification Requests" groups="stock.group_stock_manager">
                    <group>
                        <field name="slot_verification_ids" nolabel="1"/>
                    </group>
                </page>
            </notebook>
            <xpath expr="//field[@name='line_ids']/tree/field[@name='discrepancy_threshold']" position="after">
                <field name="slot_verification_ids" invisible="1"/>
                <button string="Slot Verification Request" attrs="{'invisible': [('slot_verification_ids', '=', [])]}" name="action_open_svr" type="object" icon="fa-sticky-note"/>
            </xpath>
        </data></field>
    </record>

**Comment by pedrobaeza** [comment]
This seems a problem in your deployment. It's advisable to have your Odoo server on Linux, not on Windows. Any way, out of the scope of this issue tracker.
