### ISSUE TITLE
Stock MTS+MTO Rule not using vendor minimal quantity

### ISSUE THREAD

**Issue by mattivena** [OCA/stock-logistics-warehouse#456]
Ordered quantity is not based on vendor minimal that is set on the product form. 
Ordered quantity should be: vendor minimal quantity + the needed amount.
The basic MTO rule in odoo works this way.
Tested on odoo vr.10
Thank you all for your efforts!

**Comment by gchansc** [comment]
Version 11 also doesn't take Vendor minimal qty into account. Why is that?
