### ISSUE TITLE
For some reason is not working [stock_mts_mto_rule]

### ISSUE THREAD

**Issue by ninjoan** [OCA/stock-logistics-warehouse#465]
Hello  just download and test the module but dont work....

I have the follow

Product A
 [x]Buy
 [x]Make To Order + Make To Stock

With a stock of 50

-----------------------
I crease a SO for 90 units of product A
a RFQ  is create for 90 units
--------------------------

Odoo V11 do you need some log file?

**Comment by pedrobaeza** [comment]
Which module? What do you expect to have?

**Comment by bodedra** [comment]
@pedrobaeza It seems module will be `stock_mts_mto_rule`

@ninjoan 
Can you check your configuration under company's warehouse form ? 

`'Use MTO+MTS rules'` should be checked.

Afterwards, it will use stock and generate purchase order for remaining quantity.

**Comment by ninjoan** [comment]
@bodedra can you share a print screen of where is 
`Can you check your configuration under company's warehouse form ?

'Use MTO+MTS rules' should be checked.`

Im new in Odoo still testing..

**Comment by ninjoan** [comment]
![screenshot-192 168 10 105 8069-2018-08-09-09-29-58](https://user-images.githubusercontent.com/14807878/43902048-0def9f58-9bb7-11e8-9ac2-089a670dcf05.png)

**Comment by bodedra** [comment]
@ninjoan 

Go to main menu Inventory > Configuration > Warehouse Management > Warehouses

Open company related warehouse. You will see following screen.

![screenshot from 2018-08-09 20 47 17](https://user-images.githubusercontent.com/14229503/43908639-1b7f675c-9c16-11e8-860e-e3d5e7d4d402.png)

**Comment by ninjoan** [comment]
Ohhh got it!
Nice but for some reason the inventory said Delivery Orders > 1 To Do with Ready status but not all products are in stock.

strange.....

**Comment by bodedra** [comment]
@ninjoan Sorry. I can not get your point with this information. Can you try with fresh product and do your test as per your reported issue ?

**Comment by djaouadi** [comment]
Hello,
For me also stock mts_mto rule is not working in "odoo 11.0" I don't know why, i did all configuration !!
