### ISSUE TITLE
[11.0] stock_mts_mto_rule: No procurement rule found

### ISSUE THREAD

**Issue by abdallamhafeez** [OCA/stock-logistics-warehouse#485]
Hello,
I have an issue in "stock_amts_mto_rule" when selling quantity more than onhand

Steps:
1. Flag warehouse "Use MTO+MTS rules"
2. Create a new product and mark on "Make To Order + Make To Stock" and remove any flag on other routes and add vendor
3. Update quantity on hand with 10.
4. Create a new sales order and sell 15 and confirm the order.

The message appears "No procurement rule found. Please verify the configuration of your routes"

**Comment by rousseldenis** [comment]
@abdallamhafeez Please provide the branch version you use and modules installed

**Comment by abdallamhafeez** [comment]
use 11.0 and you can test it in OCA runbot

**Comment by ghost** [comment]
@abdallamhafeez It is not an issue in my understanding. You can re-read the description of this module, you are in the 3rd case and you need to define the method to supply the remaining qty (5 unit in your case). You need to choose buy or manufacture as a supply method

**Comment by yeestrada** [comment]
Hi, I am currently using Odoo 12, but it happens the same to me, I already made the procurement rule for the product, but the system still shows me the same warning, can you tell me what to do to fix it??
