### ISSUE TITLE
stock_orderpoint_generator: suggested improvement

### ISSUE THREAD

**Issue by ccandito** [OCA/stock-logistics-warehouse#497]
Dear All,
I've tested it and all seem good.
I'd suggest to filter only stockable products so only these can be included into the list.
Regards
claudio

**Comment by pedrobaeza** [comment]
@ccandito you are free to add a PR with that suggestion.

**Comment by ccandito** [comment]
Hi,
Please send me some more details
I've not done it before
So in the future i'll be able to do it without annoying you again
Thanks in advance
Claudio

**Comment by pedrobaeza** [comment]
Well, this is something about developing. You should filter the products according that criteria.

**Comment by rousseldenis** [comment]
@ccandito Any news about this ?
