### ISSUE TITLE
stock_mts_route + mrp_mto_with_stock and BOM procurement 

### ISSUE THREAD

**Issue by eqrp** [OCA/stock-logistics-warehouse#509]
Hi at all,

First: We installed stock_mts_route and mrp_mto_with_stock

We have the following problem. We have a motherproduct 'Test Motherproduct' (Route: 'Manufacture' and 'Make To Order + Make To Stock').

![screenshot 3](https://user-images.githubusercontent.com/15906250/48336491-aee08a00-e660-11e8-9d56-01ca7eda687f.png)

This product has a bill of material with one product called 'Child Product'.

![screenshot 2](https://user-images.githubusercontent.com/15906250/48336494-b56f0180-e660-11e8-8063-9e9e4bdf0db2.png)

The routes of this 'Child Product' are 'Buy' and 'Make To Order + Make To Stock'.

![screenshot 4](https://user-images.githubusercontent.com/15906250/48336501-b99b1f00-e660-11e8-8694-3554d0fb47b0.png)

The virtual available of the 'Child Product' is 10.0 and this product has a vendor with a minimum order of 1.0.
The next step is the creation of a manufacturing order.

![screenshot 5](https://user-images.githubusercontent.com/15906250/48336509-bef86980-e660-11e8-831f-dfa326d9be0c.png)

Here you can see that we need only 15.0 pieces of
the 'Child Product' to create 100 pieces of the 'Test Motherproduct'.
10.0 is the virtual available. We need 25.0 of 'Child Product' to produce 100 pieces of 'Test Motherproduct'.

10.0 virtual available of 'Child Product' - 100 * 0,25 required quantity of 'Child Product' for MO/00046
= expected purchase order with 15.0 pieces of 'Child Product'.

So we have expected a purchase order with 15.0 of the Child Product.

How can we manage it that Odoo creates only a purchase order with the required quantity of 'Child Product' (15.0) ?

**Comment by umiphos** [comment]
```How can we manage it that Odoo creates only a purchase order with the required quantity of 'Child Product' (15.0) ?```

The current answer is, you can't right now, MTS+MTO may support the split(buy/stock) but Odoo and MRP by itself doesn't.

We have an effort in https://github.com/OCA/stock-logistics-warehouse/pull/500, but currently haven't fixed the whole problem, just fixed partially in MRP, but it will always act as a MTO route and never do the split between stock and buy. 

Related
https://github.com/OCA/stock-logistics-warehouse/issues/505

**Comment by sergiocorato** [comment]
related #572

**Comment by rousseldenis** [comment]
@eqrp In which version are you ?

**Comment by eqrp** [comment]
odoo version 10.0 Community
