### ISSUE TITLE
stock_picking_backorder_setting

### ISSUE THREAD

**Issue by max3903** [OCA/stock-logistics-warehouse#515]
Dependency: stock
License: AGPL-3

# Module description
When processing a partial transfer, Odoo Inventory App always asks if a back-order should be created or not. Some organizations have a standard policy to manage back-orders.

This module allows you to choose between the following options to set your back-order management policy:
* Always create back-orders
* Never create back-orders
* Ask if back-orders should be created or not

# Configuration
* Go to Inventory > Configuration > Settings
* There is an option "Partial Transfer" where you can select between:
  * Always create back-orders: Odoo will skip the popup window and always create a back-order for the current transfer
  * Never create back-orders: Odoo will skip the popup window, create a back-order for the current transfer and cancel it (like Odoo does when you click "No back-order")
  * Ask if back-orders should be created or not (same as the current behavior)

**Comment by pedrobaeza** [comment]
Well explained feature and interesting to be added. I think you can implement it using a context variable that allows to bypass that check. About the module name, I would go for `stock_picking_backorder_setting`.

**Comment by max3903** [comment]
Ping @mgosai

**Comment by rousseldenis** [comment]
@max3903 I'd prefer setting this option on picking type level. That's more flexible. What do you think about ?

**Comment by rousseldenis** [comment]
@max3903 Arf, I knew I did something equivalent. :smile: 
https://github.com/OCA/stock-logistics-workflow/tree/10.0/stock_picking_backorder_strategy

**Comment by pedrobaeza** [comment]
Good idea to be at picking type level, and better if it's implemented! That one has been out of my radar.

**Comment by max3903** [comment]
Closing. We'll migrate stock_picking_backorder_strategy in https://github.com/OCA/stock-logistics-workflow.

Thank you!
