### ISSUE TITLE
odoo TypeError: unlink() got an unexpected keyword argument 'check'

### ISSUE THREAD

**Issue by fdvarela** [OCA/stock-logistics-warehouse#551]
https://github.com/OCA/stock-logistics-warehouse/blob/23a60fbd9360cba7ab677b6ba1e4229e0baea48e/stock_inventory_revaluation/models/account_move.py#L37

Got another module passing a check=False to unlink and this module breaks the execution due to an

odoo TypeError: unlink() got an unexpected keyword argument 'check'

Not sure if this one is to blame but I patched my instance passing a check=True in this line and it works now.
Same would happen to the account.move unlink method

**Comment by pedrobaeza** [comment]
I have fixed it directly with a59a57ca5bf9c8b520b575fa810a14fa23055ba8
