### ISSUE TITLE
Migration of multiple addons which depends each other (so, they can't pass test)

### ISSUE THREAD

**Issue by kittiu** [OCA/stock-logistics-warehouse#560]
@lreficent @jbeficent 
So far, I have migrated the following addons. All of them pass test on my local machine. Then, I submit them individually, so it won't pass travis.
https://github.com/OCA/stock-logistics-warehouse/pull/550
https://github.com/OCA/stock-logistics-warehouse/pull/554
https://github.com/OCA/stock-logistics-warehouse/pull/557
https://github.com/OCA/stock-logistics-warehouse/pull/558
https://github.com/OCA/stock-logistics-warehouse/pull/559
I am not very sure how do we go about it...

**Comment by pedrobaeza** [comment]
There should be one that is the first for which the rest depends on. Start with that, be sure CIs pass, get it to be merged, and then continue with the rest. Meanwhile, mark the rest as WIP with a reference to which one is depending on.

**Comment by kittiu** [comment]
@pedrobaeza Thank you,

**Comment by LoisRForgeFlow** [comment]
Closing as most of these PRs are merged and the process is clearer for @kittiu
