### ISSUE TITLE
Migration of stock_mts_mto_rule V11-> V12

### ISSUE THREAD

**Issue by jvOrsouw** [OCA/stock-logistics-warehouse#565]
I'd like to receive a quote for migration of this OCA module. My customer is a V11 EE user of this module and is considering migrating to V12.

**Comment by jvOrsouw** [comment]
@florian-dacosta can you label my issue 'help wanted' or give me a quote as you're the main contributor to this module?

**Comment by gclauwae** [comment]
We have a similar request. I have asked our developer what would be the cost for migrating it. If interested I can ask my customer to share the costs.

**Comment by jvOrsouw** [comment]
@gclauwae I've also received a quote from our developer. Can we compare estimates & prices?

**Comment by gclauwae** [comment]
@jvOrsouw Can you send me your estimates to see if we can match it? gunther@beopen.be

**Comment by rousseldenis** [comment]
This is being done in #586

**Comment by astirpe** [comment]
This old issue could be closed.
