### ISSUE TITLE
stock_mts_mto_rule: doubled / multiplied consumed material when MO clicked "done" (V10)

### ISSUE THREAD

**Issue by schickermineral** [OCA/stock-logistics-warehouse#566]
Hi everybody,
we are facing an issue using stock_mts_mto_rule leading to stock differences by multiplying [consumed materials] rows in MO
-> on click "done" in MO
-> when product to be produced had only partly available stock and BOM line product had only partly available stock

E.g.:
given [product 1] (with BOM lines [product 10] having stock 1 and [product 11] having stock 10) has stock 1 but [product 1] is ordered by sale order with quantity 3:
* Procurement and MO_1 is generated for [product 1]  -> to produce = 3
* Click on "check availability" creates procurement and MO_2 for [product 10] -> to produce = 1
** producing [product 10] is all fine -> stock of [product 10] is now 2 (MO_2 = done)
* MO_1 for [product 1] can now reserve stock of additional 2 of [product 10] -> reservation of [product 1] = 3
** producing [product 1] with MO_1 is now all fine
(consumed materials - MO_1)
*** line 1 is [product 10] to consume 1 
*** line 2 is [product 10] to consume 2
*** line 3 is [product 11] to consum3 3 

- NOW -
** click "done" in MO_1
- RESULT -
(consumed materials - MO_1)
** line 1 is [product 10] to consume 1 
** line 2 is [product 10] to consume 2
** line 3 is [product 10] to consume 2 <- doubled !
** line 4 is [product 10] to consume 1 <- doubled !
** line 5 is [product 11] to consum3 3
(finished products - MO_1)
** line 1 is [product 1] to produce 3, produced 3
- BUT - 
** consumed of [product 10] = 6 instead of 3

(see screenshots attached)
![product_1_MO_1_consumed_materials](https://user-images.githubusercontent.com/41774780/54926438-9fc3ef80-4f10-11e9-9b5d-1e33ac276b34.png)
![product_1_MO_1_finished_products](https://user-images.githubusercontent.com/41774780/54926439-a05c8600-4f10-11e9-92fa-a6ddc58861e5.png)
![routes](https://user-images.githubusercontent.com/41774780/54926440-a05c8600-4f10-11e9-99d4-1281bbad8498.png)

Thanks in advance for your feedback!
If any additional info is needed let me know.

Best,
Michael

**Comment by rousseldenis** [comment]
@florian-dacosta 

It's a recurrent problem. We should maybe do a document to gather facts and helps a possible refactoring.

What do you think ?

**Comment by florian-dacosta** [comment]
Hi @rousseldenis 
About this particular issue, I do not really understand the case, and I also dot not really see how we could confirm it comes from the stock_mts_mto_rule (I do not think it does).

Anyway, I think there are 2 main issues : 

1) Missunderstanding on what is covered by the module. 
This module manage the case of choosing make to stock or make to order method when facing a procurement. (Usually when confirming a sale order). It does not cover the manufacturing part. (procure or not the raw material of a Manufacturing order) neither does it depends on mrp module.
Another module manage this in the manufacture repository : mrp_mto_with_stock.
This last module does not depends on stock_mts_mto_rule and manage things in an other way unfortunately. I think this manufacturing module should be refactored to depend on stock_mts_mto_rule.

Anyway, the first step should probably be to update the stock_mts_mto_rule readme, to explain clearly that this module do not manage the manufacturing part as most people expect.

2) The module may need complex configuration. 
If you use default Odoo rules, only one stock location, etc... you won't have to configure anything to make it work. But, if you have a more complex warehouse management with multiple locations, multiple delivery steps, etc... It may required to change the route/rules configuration... And this is complex and not possible for a random user. In these case also I guess it can bring issues to users.

But the real main issue, I think, is the 1)

**Comment by rousseldenis** [comment]
@schickermineral Could you look at @florian-dacosta comments and give us feedback?

**Comment by schickermineral** [comment]
Hi @florian-dacosta,

first of all thank you very much for your feedback and clarifications which is highly appreciated.

> 1. Missunderstanding on what is covered by the module.
This module manage the case of choosing make to stock or make to order method when facing a procurement. (Usually when confirming a sale order). It does not cover the manufacturing part. (procure or not the raw material of a Manufacturing order) neither does it depends on mrp module.
Another module manage this in the manufacture repository : mrp_mto_with_stock.
This last module does not depends on stock_mts_mto_rule and manage things in an other way unfortunately. I think this manufacturing module should be refactored to depend on stock_mts_mto_rule.

You are right, we are using the module "mrp_mto_with_stock" as well, and we indeed assumed the interaction would work smoothly as both are distributed by OCA. But we understand both modules are currently not coordinated depending on each other.

> I think this manufacturing module should be refactored to depend on stock_mts_mto_rule.

This would be very welcome. The question is how likely this actually will be scheduled to be impemented?
Re-implementation request +1 ;)

> 2. The module may need complex configuration.
If you use default Odoo rules, only one stock location, etc... you won't have to configure anything to make it work. But, if you have a more complex warehouse management with multiple locations, multiple delivery steps, etc... It may required to change the route/rules configuration... And this is complex and not possible for a random user. In these case also I guess it can bring issues to users.

Indeed we are using complex warehouse management with multiple locations and automated generation of delivery notes for transfers between locations, which works quite fine with odoo standard functions.
Just some special constellation, that is still unclear, causes that behavior in manufacturing using module [mrp_mto_with_stock]. So most likely topic needs to be adjusted or a new one to be opened!?

We are open to provide further information to help finding the cause as a reimplementation basis.

Looking forward to your further findings.
Best,
Michael

**Comment by florian-dacosta** [comment]
> But we understand both modules are currently not coordinated depending on each other.
Actually, they can work together. They just use different mechanisms and the configuration on the product is different for a product used as raw material for production and a product that is sold for instance. (first one managed by mrp_mto_with_stock and second one managed by stock_mts_mto_rule)

But anyway, you should not have a problem of production orders consuming too much raw material with both modules installed. But I am quite sure it does not come from mrp_mto_mts_rule.
And I don't really see how it could come from mrp_mto_with_stock either actually.

@schickermineral  Would you be able to reproduce the problem on runbot?

**Comment by schickermineral** [comment]
@florian-dacosta 
I'd give it a try when I find an appropriate runbot instance.
Can you give a hint regarding where to reproduce, because we're not yet experienced using runbot especially how to install OCA modules in such instance.
Thanks!

**Comment by rousseldenis** [comment]
@schickermineral What's the status of this ?

**Comment by schickermineral** [comment]
> @florian-dacosta
> I'd give it a try when I find an appropriate runbot instance.
> Can you give a hint regarding where to reproduce, because we're not yet experienced using runbot especially how to install OCA modules in such instance.
> Thanks!

Status unchanged since my last post. We were waiting for some input how to test on runbot.

Indeed we are going to not use [mrp_mto_with_stock] anymore in the near future (currently testing). So we will see whether this leads to preventing mulitplied consumption though, which was one assumption in an earlier post of @florian-dacosta. 

At this point we are facing multiplied consumption only sporadically but can't find a pattern why.

We'll keep you posted whether this was the solution indeed.
