### ISSUE TITLE
MTS+MTO - BOM in BOM isue

### ISSUE THREAD

**Issue by michaelsallaberger** [OCA/stock-logistics-warehouse#572]
Hy Guys,

I want to produce a product according to a BOM and this BOM contains a BOM of another product.

If I choose MTO (only) for both products, and sell the product which is on the top of the BOMs,
the system generates a MO for each product and the deadline start will be choosen according to the manufacturing lead time of each product. (This is 100% correct)

If I choose MTS+MTO for both products, and sell the product which is on the top of the BOMs,
the system generates a MO only for the BOM which is on the TOP, not for the BOM which is contained in the BOM on the top.

Can anybody help me, please?

**Comment by florian-dacosta** [comment]
@michaelsallaberger You should take a look at this module https://github.com/OCA/manufacture/tree/11.0/mrp_mto_with_stock and test it, it should meet your need.

**Comment by sergiocorato** [comment]
I found the same problem in v. 12.0, as of abandoned #500 for v. 11.0 it seems the bug is not resolved.

**Comment by sergiocorato** [comment]
[This](https://github.com/OCA/manufacture/pull/411) solve for v. 12.0, but I do not investigated so much.
