### ISSUE TITLE
Stock Cycle Count for Version 12

### ISSUE THREAD

**Issue by jlholzbach** [OCA/stock-logistics-warehouse#578]
I am trying to add Stock Cycle Count to version 12 of Odoo Community, because it would be helpful for my organization, but am having some compatibility issues since the most recent version is for Odoo 11. Is there update on it being updated for 12? 

Most of my problems seem to with fields not existing, but I am also getting some errors like this     

raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view stock.cycle.count.search definition in stock_cycle_count/views/stock_cycle_count_view.xml
None" while parsing file:/d:/odoo%2012.0/server/odoo/addons/stock_cycle_count/views/stock_cycle_count_view.xml:72

I came across this migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0, and was wondering is there any risking associated from manually making these changes to attempt to get the module working. We could go to Community version 11 if we had to, but would prefer not having to do that.

**Comment by rousseldenis** [comment]
@lreficent @jbeficent

**Comment by LoisRForgeFlow** [comment]
The module has been recently migrated to v12, an should be already available.

**Comment by normalperson16** [comment]
odoo 13 File "/opt/odoo/addons/stock_account/models/stock_move.py", line 254, in _action_done
    for move in res - self:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'stock.move'
