### ISSUE TITLE
stock_request: Support routes

### ISSUE THREAD

**Issue by max3903** [OCA/stock-logistics-warehouse#587]
We use `stock_request` to allow employees of other departments to request materials in a location, i.e. FSM User or Helpdesk User may want a product to be returned or shipped to a customer.

As the material can take different routes:
* shipped from the warehouse with a carrier (Delivery Order)
* loaded on a truck and delivered by the company to the customer

we would like to:
- [ ] add a boolean field "Stock Requests" (stock_request_selectable) on stock.location.route
- [ ] add a many2one field "Route" (route_id) field on stock.request. The list would be filtered based on stock_request_selectable

When the stock request is confirmed, a procurement is created at the destination location and the specified route is triggered to create the stock pickings.

**Comment by max3903** [comment]
Ping @jbeficent @etobella @aisopuro @BT-rmartin

**Comment by JordiBForgeFlow** [comment]
@max3903 but the route_id is already in the stock.request
https://github.com/OCA/stock-logistics-warehouse/blob/12.0/stock_request/models/stock_request.py#L99
https://github.com/OCA/stock-logistics-warehouse/blob/12.0/stock_request/views/stock_request_views.xml#L16

It will display all the rules that are available to that location.

Isn't that enough?

**Comment by max3903** [comment]
@jbeficent Oh true, thanks.

BTW, the dropdown list is empty:
http://3367889-12-0-6720ef.runbot1-2.odoo-community.org/web?debug#id=1&action=329&model=stock.request&view_type=form&menu_id=195

**Comment by JordiBForgeFlow** [comment]
@max3903 I just accessed and it's not empty. Have you changed it?

![image](https://user-images.githubusercontent.com/7683926/57538694-42adbd00-7349-11e9-9d4a-7fb745a7c036.png)

**Comment by max3903** [comment]
@jbeficent Yes, I changed the location.

If you create a new request with the Stock location, there is no choice...

**Comment by JordiBForgeFlow** [comment]
@max3903 Because there's no valid route applicable to WH/Stock.

I have just created a route WH2->WH. Check SR/00003

In the product I defined what routes should be used:
![image](https://user-images.githubusercontent.com/7683926/57539177-3118e500-734a-11e9-9d21-047b9850f017.png)

**Comment by max3903** [comment]
Thanks!
:+1:
