### ISSUE TITLE
Domain on wizard locations ?

### ISSUE THREAD

**Issue by mcassuto** [OCA/stock-logistics-warehouse#59]
Hi,

I wonder why
- the wizard source location is not the sale_order.warehouse_id.lot_stock_id (the main stock location for the sale order Warehouse) by default
- the list of destination location are not the customer location by default ?

Usually a sale person sales from stock to customer...

**Comment by pedrobaeza** [comment]
Which module?

**Comment by pedrobaeza** [comment]
No answer, so I close.
