### ISSUE TITLE
[IMP] stock_request: Add a "Submitted" state

### ISSUE THREAD

**Issue by max3903** [OCA/stock-logistics-warehouse#595]
# Requirement

Users from other departments than the Warehouse uses stock requests to specify where products needs to be and when. This can be done from a project task, help desk ticket or field service order. Users may make modifications before the requests get processed by the warehouse team.

# Current module

The current module provides the following states: Draft, In Progress, Done, Cancelled.

# Change

We would like to add a new state "Submitted" between Draft and In Progress so the other teams can make modifications to their requests before it is submitted and showing up on the radar of the Warehouse team.

What do you think?

**Comment by max3903** [comment]
Ping @jbeficent @patrickrwilson @wolfhall

**Comment by etobella** [comment]
It's a good option, but could you add a parameter in order to allow this new state? This way we can maintain the old functionality with the new one

**Comment by rousseldenis** [comment]
@max3903 And what about https://github.com/OCA/stock-logistics-warehouse/tree/11.0/stock_request_tier_validation

That is more compliant to your business flow requirement no ?

**Comment by max3903** [comment]
@rousseldenis How would you configure it using stock_request_tier_validation? What happens when the user create the stock request?

We would like to hide the draft records to the Warehouse users.

**Comment by rousseldenis** [comment]
> We would like to hide the draft records to the Warehouse users.

Ok, maybe misunderstood your requirements.

Do your flow first create request, secondly review request and then submit to warehouse users ?

Is that correct?

**Comment by max3903** [comment]
Internal User:
* create stock requests
* come back later and modify it.
* when ready, submit to Warehouse user

Warehouse User:
* Review submitted requests
* Make modifications
* Confirm

There is no review or validation step.

**Comment by JordiBForgeFlow** [comment]
I would add it as a new state, and through the settings decide if you want to use it.

Something like:
[ ] Allow user to submit stock requests.

In the line that @etobella suggests.

**Comment by max3903** [comment]
:+1: Thank you. We will work on it. Please expect the pull request to review next week.
