### ISSUE TITLE
Please help to migrate "stock_reserve_sale" to v12.

### ISSUE THREAD

**Issue by hzh0292** [OCA/stock-logistics-warehouse#613]
I tried to migrate "stock_reserve_sale"  to V12 but failed.
And this is a useful app.
I asked that wherther OCA have the plan to migrate it to v12 or give me some advise to do this work.
Thanks very much!

**Comment by pedrobaeza** [comment]
In which things you have failed? You can ask for assistance in an specific problem, but not this general request.
