### ISSUE TITLE
Migration of stock_reserve_sale to v12 but found bugs

### ISSUE THREAD

**Issue by hzh0292** [OCA/stock-logistics-warehouse#619]
[Odoo module stock_reserve_sale migration to verssion 12.0](https://github.com/hzh0292/stock-logistics-warehouse)

1. The basic module stock_reserve is migrated from OCA/stock-logistics-warehouse branch 10.0.
2. The module stock_reserve_sale is migrated from OCA/stock-logistics-warehouse branch 9.0.Because the branch 10.0 of this module is unfinished yet and it was based version 8.0.
3. I replaced the old model 'procurement.rule' to 'stock.rule' in stock_reserve_sale/model/sale.py,and did some normal odoo 12.0 migration stuff.
4. Because I don't know much about odoo module development, I didn't modified the logical code.
5. This two modules can installed in odoo 12,and most of the functions work well.But I found a bug that when you create a stock reservation from a sale order which contain 2 or more lines,there will be a 'Odoo Server Error' show that Record does not exist or has been deleted.And the console will show a message like 'odoo.models.unlink: User #1 deleted stock.move records with IDs: [41]'.

![](https://i.bmp.ovh/imgs/2019/06/e3ec4a8e3bffe28f.png)

![](https://i.bmp.ovh/imgs/2019/06/c289c3ea59781563.png)

**Comment by hzh0292** [comment]
Can somebody help me solve the bugs?

**Comment by damendieta** [comment]
Hi, do the MR in order to have this migration there.

I'll try to install the modules and check the possible causes of the issue.

Daniel.

**Comment by hzh0292** [comment]
> Hi, do the MR in order to have this migration there.
> 
> I'll try to install the modules and check the possible causes of the issue.
> 
> Daniel.

Thanks very much.It seems that I don't know how to do the MR.

**Comment by hzh0292** [comment]
> Hi, do the MR in order to have this migration there.
> 
> I'll try to install the modules and check the possible causes of the issue.
> 
> Daniel.

I have created a new pull request to this repo.Is it the right way to do a MR?[#620](https://github.com/OCA/stock-logistics-warehouse/pull/620)

**Comment by damendieta** [comment]
Hi, I'm checking the code and I have some comments:

- stock_reserve_sale should depend on sale, as you are inheriting sale.order
- you have except_orm but it's deprecated, replace it with an exception from the new api.
- The error is happening on line 140, of stock_reserve.py 
   self.mapped('move_id')._action_confirm()

After the move is confirmed, the move is unreacheable.

**Comment by hzh0292** [comment]
> Hi, I'm checking the code and I have some comments:
> 
> * stock_reserve_sale should depend on sale, as you are inheriting sale.order
> * you have except_orm but it's deprecated, replace it with an exception from the new api.
> * The error is happening on line 140, of stock_reserve.py
>   self.mapped('move_id')._action_confirm()
> 
> After the move is confirmed, the move is unreacheable.

+ Yes,this module depend on sale,I didn't add it because the original version didn't write it.
+ The except_orm is deprecated.I will replace it with the new api.
+ I have changed the code here,the old version is ```self.mapped('move_id').action_confirm()```.Since it is so,is there any solution to solve this error?
Thank you very much!

**Comment by damendieta** [comment]
Hi, I have commented on the code of the pull request.

**Comment by hzh0292** [comment]
> Hi, I have commented on the code of the pull request.

Thanks very much.But I don't see your comment,can you tell me where is it?

**Comment by damendieta** [comment]
> > Hi, I have commented on the code of the pull request.
> 
> Thanks very much.But I don't see your comment,can you tell me where is it?

Check the PR history, it will show up on the first screen. You didn's saw it before because I was adding a last comment, so, It wasn't available to you yet :D

Please, also check the commit history as Pedro explained to you.

Daniel.

**Comment by hzh0292** [comment]
Solved.
