### ISSUE TITLE
RFC: weighting scales integration

### ISSUE THREAD

**Issue by ivanvashenko12** [OCA/stock-logistics-warehouse#624]
We are looking for the way of direct integration with weighting scales in warehouse module.

### **The idea/ objective**
Add the way of entering data for weighted products directly from the scales by simple press of buttons.

### **Technical description for Definition of the reservation**
inventory move adjustments:

- add buttons for operating with scales:

1. print weight
2. tare scales
3. zero scales

### **Expected Behavior**

After pressing the print weight button, weight from the scales should be transferred to the active "done" field.
Pressing the "tare" or "zero" buttons should just send the command to the scales.

**### Technical Solution**
Using the Google chrome API (serial) or the qz.io , connect the scales directly to the client machine. All settings about the scales (commands, baud, stopbits, etc) should be done on clients side.

**Comment by pedrobaeza** [comment]
Hi @ivanvashenko12, did you get something about this?

**Comment by rousseldenis** [comment]
@ivanvashenko12

**Comment by rousseldenis** [comment]
Maybe you can take a look at https://github.com/akretion/pywebdriver

The weight driver is mising but I think this gap could be fullfilled
