### ISSUE TITLE
Documentation / Features / Demo?

### ISSUE THREAD

**Issue by supersexy** [OCA/stock-logistics-warehouse#662]
I found this via a DDG search - is there any documentation / feature description / screenshots or does exist a related website that describes these modules, maybe with a demo install? Thanks!

**Comment by rafaelbn** [comment]
Hello,

There is a lot of documentation, every single module has a Readme where explain description, configuration and usage, and YES you have a demo install for every module

You will find the information in:

- https://odoo-community.org/
- https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst

Regards

**Comment by supersexy** [comment]
AH, ok - you should put that info in the main readme, thanks for the quick reply!
