### ISSUE TITLE
[12.0] stock_request: losing partner_id and origin

### ISSUE THREAD

**Issue by max3903** [OCA/stock-logistics-warehouse#664]
# Steps to reproduce

* Create a field service order with a location
* Add 2 stock requests to that field service order --> A stock request order is created with 2 lines.
* Click Submit
* Go to the submitted stock request order
* Confirm the stock request order

# Result

A delivery order is created but the partner_id and the origin are not set.

# Expected Result

A delivery order is created and the partner_id is set to the location of the field service order and the origin is set to the stock request order.

# Explanations

* The stock request module sets the origin of the stock move to the stock request name:
https://github.com/OCA/stock-logistics-warehouse/blob/12.0/stock_request/models/stock_request.py#L282
* Odoo resets the partner_id and origin of the picking if the moves do not have the same origin:
https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_move.py#L696

# Proposed solution

* Set the origin of the stock.move to the stock.request.order if the request is linked to an order:

```
class ProcurementGroup(models.Model):
    _inherit = 'procurement.group'

    @api.model
    def run(self, product_id, product_qty, product_uom, location_id, name,origin, values):
        if 'stock_request_id' in values and values.get('stock_request_id'):
            req = self.env['stock.request'].browse(values.get('stock_request_id'))
            if req.order_id:
                origin.req.order_id.name
        return super().run(product_id, product_qty, product_uom, location_id, name, origin, values)
```

**Comment by max3903** [comment]
Ping @etobella @rousseldenis @jbeficent

**Comment by bodedra** [comment]
@max3903 We can close these as proposed PR is merged. Ref: https://github.com/OCA/stock-logistics-warehouse/pull/665
