### ISSUE TITLE
Inactive location

### ISSUE THREAD

**Issue by max3903** [OCA/stock-logistics-warehouse#68]
# stock_location_inactive

This module allows you to check that:
- a location is empty (no product)
- a location has no active sub-locations

before setting it as inactive. 

It also modify the Inventory Analysis report to hide inactive locations.
# Usage
- Go to Warehouse > Configuration > Locations
- Try to deactivate a location
- Go to Reporting > Warehouse > Inventory Analysis
- A grouping by location will not display inactive locations

**Comment by clonedagain** [comment]
@lbellier can you please follow this development? we definitely need this too.
@max3903 please add 8.0 to the rodamap, we can offer our help porting to new API if you want.

**Comment by pedrobaeza** [comment]
Closing as PR merged.
