### ISSUE TITLE
[11.0] stock_putaway_same_location wrong on new main warehouse

### ISSUE THREAD

**Issue by infoitservit** [OCA/stock-logistics-warehouse#682]
Steps to reproduce:

1) Install stock_putaway_same_location
2) Make a purchase to ship to the actual default main warehouse and receive goods. Complete receipt on "WH/Stock".
3) Create a new warehouse, it should be your new main warehouse where all the receipts will came in.
4) On New Warehouse/Stock set putaway strategy as "last position", as per normal configuration of stock_putaway_same_location.
5) Make a purchase setting the operation type as "New Warehouse: receipt"
6) Take a look at the receipt form: you'll find that the destination of the goods is "New Warehouse/Stock" but on the operation lines the destination is "WH/Stock", so the old Warehouse main stock location.

**Comment by rousseldenis** [comment]
@infoitservit This is known by the author, see: https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_putaway_same_location/models/product_putaway.py#L26

Maybe, you can propose a PR to change this?
