### ISSUE TITLE
[RFC] Different destination location in inventory adjustments

### ISSUE THREAD

**Issue by MiquelRForgeFlow** [OCA/stock-logistics-warehouse#714]
Hi @rousseldenis @GillesTephaneMeyomesse,

We would like to allow users to change the destination location in inventory adjustments. Instead of the application defaulting to the product's default inventory location, the user would be able to indicate a different location while performing an inventory adjustment.

This is interesting, for example, for accounting purposes, if you use perpetual inventory, because some inventory adjustments should be posted to specific accounts. And the choice of the account to be used is determined by the inventory virtual location.

We plan to create a module 'stock_inventory_adjustment_location_change' to do that.

Furthermore we'd like to create a module that connects with `stock_change_qty_reason`. When the users indicates a reason from the selection, it could automatically propose a different inventory location. This location would be optional in the reason definition.

While studying the feasibility of this concept, we though that maybe would be better to improve the `stock_change_qty_reason`, adding this feature. What do you think of this idea? As you are the creators of that module, we want to hear your opinion. Would you like to have this idea implemented in the `stock_change_qty_reason` module or do you prefer to be handled in different modules?

cc: @jbeficent @hveficent

**Comment by rousseldenis** [comment]
@mreficent So, you need both functionnaliies of reason change and location change ?

As your feature (the location proposal related to reason) depends on stock_change_qty_reason, I think you could reasonably make a new module depending on it ? Wthat do you think?

**Comment by MiquelRForgeFlow** [comment]
Yeah, that's why I did a glue module (same PR as the other).
