### ISSUE TITLE
created only for company_id=1 [stock_mts_mto_rule]

### ISSUE THREAD

**Issue by jwaes** [OCA/stock-logistics-warehouse#725]
"Make To Order + Make To Stock" entry in db table stock_location_route gets created only with company_id=1

In a multi company setup the other companies do not have the option available.

**Comment by rousseldenis** [comment]
@jwaes Could you say in which version it happens ?

@florian-dacosta

**Comment by jwaes** [comment]
Odoo 12.0-20190816 (Community Edition)

    'name': 'Stock MTS+MTO Rule',
    'summary': 'Add a MTS+MTO route',
    'version': '12.0.1.0.0',

**Comment by rousseldenis** [comment]
I think route is created at Warehouse creation.

Could you try to create a new Warehouse in your other company(ies) ?

**Comment by jwaes** [comment]
Indeed when creating a new warehouse it works ... but i had 2 companies with 2 warehouses before i installed the module.

**Comment by jwaes** [comment]
I am not able to create new rules under the Make To Order + Make To Stock route.

I tried on the runbot

http://3387252-12-0-f7509d.runbot2.odoo-community.org

![screenshot](https://cdn1.imggmi.com/uploads/2019/9/25/3c9e541f98156611ad4c4d9784495934-full.png)

The MTS Rule and MTO Rule stay empty and because of that you cannot save the Route.
