### ISSUE TITLE
stock_available don't "work" with product variants

### ISSUE THREAD

**Issue by erocre** [OCA/stock-logistics-warehouse#73]
If you work with product.product, the field "immediately_usable_qty" shows stock of product.template so the quantity is wrong

![image](https://cloud.githubusercontent.com/assets/10234023/9371890/f32117be-46d8-11e5-8176-e1d01839d232.png)

**Comment by pedrobaeza** [comment]
@clonedagain, can you please check it?

**Comment by clonedagain** [comment]
I think I notices something of this kind during the v8 review but we concluded it was OK , but maybe it is not after all. @lbellier and I are off for 2 week but we'll check it son.

**Comment by clonedagain** [comment]
Indeed we must compute the quantities for the variants first, and make a distinct method to sum the quantity for the templates - that's what the standard does anyway.
I'll add that to my current PR.

**Comment by clonedagain** [comment]
@erocre could you please test the branch https://github.com/numerigraphe/stock-logistics-warehouse/tree/8.0-stock_available-based-on-virtual and let met know if it fixes this issue?

**Comment by erocre** [comment]
:+1: checked and fixed. I will close the issue if you don't have anything to say

**Comment by clonedagain** [comment]
I think it will be closed automatically when the corresponding PR is merged : https://github.com/OCA/stock-logistics-warehouse/pull/80
