### ISSUE TITLE
cycle counting x product

### ISSUE THREAD

**Issue by ccandito** [OCA/stock-logistics-warehouse#731]
Dear All,
I've noticed cycle counting rules can be assigned to locations/warehouses only, but not to products.
Assigning a periodic rule to a product, according to an ABC classification it is possible to plan how many times a physical inventory has to be performed in a fiscal year per product.
please contact me for more information.
Regards
claudio Candito

**Comment by rousseldenis** [comment]
@jbeficent @lreficent

**Comment by LoisRForgeFlow** [comment]
It is not a good idea to perform a cycle count strategy by product, as a product can be spread across many locations in your warehouse and you should move to each location to check the qty in each location, this is not efficient. 

if you want to follow an ABC strat you need to store products of each category in different locations and then apply different rules to each group of locations.

**Comment by ccandito** [comment]
Dear Ireficente,
the purpose of cycle counting is to spread up the physical inventory effort over the year.
I'd suggest to calculate ABC indicator per warehouse, so only one class, e.g. B class, is assigned to a product per warehouse.
For each class, the number of physical inventory is assigned, e.g. 4 times per year, so every 365/4 days an physical inventory has to be performed.
in this way we can decide when a physical inventory activity has to be performed.
for any detail, please don't hesitate to write me at claudio.candito@gmail.com
regards
claudio

**Comment by LoisRForgeFlow** [comment]
I know what cycle counting is for... as I said it is not that I don't understand what you mean, it's that I don't agree how you want to implement an ABC strategy. I highlight again that the fact that the feature to cycle count by product is not there **by decision** (for the reasons exposed above).

If you still want to it that way, you can create a custom module, but I would suggest you to first read [this book](https://www.amazon.com/Cycle-Physical-Inventory-Design-Execution/dp/0557369355/ref=sr_1_1?keywords=cycle+count&qid=1571737250&sr=8-1) or any other documentation on how to properly cycle count. In the other hand, If you want to extend the app to assist the assignation of location in putaway strategies regarding an ABC criteria which then will be compatible with an ABC cycle count strategy (which for me would be the way to go) I would be more than glad to review and include that feature under OCA.
