### ISSUE TITLE
physical inventory report

### ISSUE THREAD

**Issue by ccandito** [OCA/stock-logistics-warehouse#732]
Dear All,
it is important to check that a product has been counted at least once in a fiscal year per warehouse.
I was not able to find this kind of report.
could you please advice me?
Regards
claudio

**Comment by rousseldenis** [comment]
> Dear All,
> it is important to check that a product has been counted at least once in a fiscal year per warehouse.
> I was not able to find this kind of report.
> could you please advice me?
> Regards
> claudio

You want to say that the product has to be in an inventory once a year ?

For my knowledge, there is no report for that specific needs today. Do you want to develop that feature or ... ?

**Comment by ccandito** [comment]
thanks for your reply.
unfortunately I'm not so able to develop it.
regards
claudio
