### ISSUE TITLE
[BUG][11.0] stock_inventory_exclude_sublocation: change in Odoo

### ISSUE THREAD

**Issue by rousseldenis** [OCA/stock-logistics-warehouse#736]
@mreficent @lreficent 
The 11.0 main branch is red due to a change in Odoo core :

https://github.com/odoo/odoo/commit/7b29911d0ce633998e30546230bb46abf7952518

This is a new constraint to check if products are equivalent on move line level and lot level.

Could you check or point someone else to explore for a fix ?

**Comment by rousseldenis** [comment]
I've done it :smiley:

**Comment by LoisRForgeFlow** [comment]
Thanks!
