### ISSUE TITLE
It is not possible to unreserve more products of

### ISSUE THREAD

**Issue by Qamar-Datasmith** [OCA/stock-logistics-warehouse#750]
Hi

I am trying to create stock request in Odoo version 12 through web service. Stock Request and picking created in odoo but when i click on "In transit" type picking and then click on "Validate" button then It asked me "You have not recorded done quantities yet, by clicking on apply Odoo will process all the reserved quantities." Then i click on "Apply" button it gives me error "It is not possible to unreserve more products of" .

Can anybody help me why i am getting this error what i am missing when create stock request through web service.

Attached is the error

![image](https://user-images.githubusercontent.com/39196097/68697715-3b3dc980-05a1-11ea-8098-3cf8572759c2.png)

**Comment by rousseldenis** [comment]
Do you speak about the OCA module stock_request ?

If yes, @JordiBForgeFlow @LoisRForgeFlow maybe this is a question for you

**Comment by LoisRForgeFlow** [comment]
@Qamar-Datasmith did you try on runbot? are you able to reproduce the problem?
