### ISSUE TITLE
stock_inventory_preparation_filter: Test on runbot from OCA was not successful

### ISSUE THREAD

**Issue by ybofr** [OCA/stock-logistics-warehouse#76]
Hi,

I wanted to select on product category that contains two products. I was able to select the product category, but nothing happened related to the filtering. No product came listed below. And when I tried to add a product manually, it came on the top, where I should only select the categories.

It looks to me as if something is wrong in the module and it did not work at all as I was expecting.

Basically, there is no filtering. The module at the moment allows to indicate a filter, but nothing else is happening. Looks to me like a bug, but I'm not sure the way, it was meant to work.

I have retested it, I can for instance select products, they will appear on the upper screen part, but not as line detail for the inventory. So, it really does not seem to work.

Picture was added.

<img width="1005" alt="inventory_adjustments_-_odoo" src="https://cloud.githubusercontent.com/assets/7601880/9450308/d51c87c4-4a9f-11e5-9f5d-667189931566.png">

**Comment by pedrobaeza** [comment]
Hi, Eva, you're misunderstanding inventory (in general) behaviour: the only lines added are the ones who already contains some stock. This is the standard behaviour with the existing filters, and the expanded ones only restrict the initial selection to look for.

For these case, I see that you have added two products (eva test 1 raw and eva test 2 raw), but without stock, there will be no line in this inventory. I have added 5 units for the product 1, and make another inventory, and you can see that there's a line now with this 5 units.

For Odoo, no line means quantity 0. That's understandable in many cases for example when restricting to an specific location (how to decide if an element should go here with 0 quantity), but this is a debate for doing with Odoo itself.
