### ISSUE TITLE
[11.0] stock_request broken CI because of some Odoo upstream change

### ISSUE THREAD

**Issue by chienandalu** [OCA/stock-logistics-warehouse#769]
`11.0` build is now broken. An example of the error https://travis-ci.org/OCA/stock-logistics-warehouse/jobs/612365669#L1646

Can you take a look @lreficent ?

**Comment by LoisRForgeFlow** [comment]
It should be fixed now, just rebase your branch!

**Comment by chienandalu** [comment]
Thanks!
