### ISSUE TITLE
stock_mts_mto_rule...Question?

### ISSUE THREAD

**Issue by jaronemo** [OCA/stock-logistics-warehouse#78]
Dear sir

The virtual stock is more than 0 but less than ordered quantity
=> On part of the products will be taken from stock and a purchase order
will be created for the rest. So it will act like both make to order and make to stock rule.

This module is a good intention. Thank you for the very offer.
However, it seems the business model is actually a little gap, and did not consider supply of products from manufacture to.

When the product is in stock, insufficient number generated by the production of a single source for MTS Rule ....
The actual business is to be less than that will be more in line with the MTO Rule realities
example test:
![image](https://cloud.githubusercontent.com/assets/8476734/9720259/10268a8e-55bf-11e5-9122-990a2508f1f0.png)

**Comment by pedrobaeza** [comment]
Please propose a PR with the enhancement if you see the behavior incorrect.
