### ISSUE TITLE
Is the mts-mto route applicable having a bom ?  [stock_mts_mto_rule]

### ISSUE THREAD

**Issue by mrgoetz** [OCA/stock-logistics-warehouse#825]
Hi, we want to use stock_mts_mto_rule for the production of products with boms with several layers. Lets say we want to manufacture a table. Last step of production is to paint it. The table is manufactured in several steps before.. If the virtual stock is empty for our ready painted table we see the mto_mts route active, a MO is created, but there is no procurement to produce the raw table. Is something wrong in our setup (we set the mts_mto for all products we need) or is the route only for the first layer of a bom. We use version 10.0.1.0.3. Thank you

**Comment by rousseldenis** [comment]
@florian-dacosta @LoisRForgeFlow

**Comment by florian-dacosta** [comment]
HI @mrgoetz 

Indeed, this module only work for the first layer of a bom.
For manufacturing orders'raw material, there is another module : https://github.com/OCA/manufacture/tree/10.0/mrp_mto_with_stock

**Comment by mrgoetz** [comment]
Hi Florian, thank you for your advice. This is what we need. I will close my question. Cheers
