### ISSUE TITLE
Create a default procurement.rule with 'split_procurement' action when installing module stock_mts_mto_rule

### ISSUE THREAD

**Issue by gabrielo77** [OCA/stock-logistics-warehouse#83]
I can do this, add an xml data file to automatically creates a default procurement.rule with 'split_procurement' action. Let me know if you're interested in this feature. Or state in the README file that you have to create a custom rule to get this module working.

Greetings

**Comment by florian-dacosta** [comment]
Actually, the rule should be created automatically, when you check the field "Use MTO+MTS rules" on the warehouse form view.
But, you are right, if you missed it, we should improve the README file

regards

**Comment by gabrielo77** [comment]
I didn't realize that I had to set this option on the warehouse! Thank you, it worked!

**Comment by StefanRijnhart** [comment]
Closing this as it was fixed by your contributed lines of documentation.
