### ISSUE TITLE
[13.0] [BUG]"stock_available_unreserved" module > Error when Update Quantity " from any storable product form

### ISSUE THREAD

**Issue by NCS-75** [OCA/stock-logistics-warehouse#836]
When trying to "Update Quantity" from any storable product form. There is an error message: 
`AssertionError: precision_rounding must be positive, got 0.0`

Context : OCB 13.0 Odoo Server up to date, with Virgin database , to reproduce issue faced on my test environnement, and"stock_available_unreserved" installed.

@LoisRForgeFlow 
> Also same issue on : [http://3406083-13-0-6171b7.runbot1.odoo-community.org/](http://3406083-13-0-6171b7.runbot1.odoo-community.org/)

.
See attach picture....
![_FURN_0789  Individual Workplace - Odoo](https://user-images.githubusercontent.com/59052920/73204883-1ab4f280-4140-11ea-94a6-a8ff6e70327a.png)
![Update Quantity - Odoo](https://user-images.githubusercontent.com/59052920/73204752-cc075880-413f-11ea-8ba2-4022ac197e2b.png)

**Comment by LoisRForgeFlow** [comment]
Being fixed here: https://github.com/OCA/stock-logistics-warehouse/pull/834

**Comment by LoisRForgeFlow** [comment]
This should be fixed as the PR stated above is merged.
