### ISSUE TITLE
Maximum recursion depth exceeded when running scheduling in stock_mts_mto_rule

### ISSUE THREAD

**Issue by gabrielo77** [OCA/stock-logistics-warehouse#84]
Hello,

After installing this module the procurement scheduling is aborted because of a RuntimeError: maximum recursion depth exceeded exception. I see that run() method on odoo procurement calls _run() method, which, in your stock_mts_mto_rule  recalls run(), and this leads to the recursion error.

Some of did face this issue too?

**Comment by pedrobaeza** [comment]
It seems nobody faces it, so I close.
