### ISSUE TITLE
modification 

### ISSUE THREAD

**Issue by eltyar** [OCA/stock-logistics-warehouse#859]
there's just one thing missing in last step, it should check Reordering Rules for Minimum & Maximum Quantity to add it to purchase order. it will be perfect if you modify it.

**Comment by rousseldenis** [comment]
> there's just one thing missing in last step, it should check Reordering Rules for Minimum & Maximum Quantity to add it to purchase order. it will be perfect if you modify it.

What's the purpose of this issue ? Could you clarify ?
