### ISSUE TITLE
I've translated some modules to german

### ISSUE THREAD

**Issue by Netzvamp** [OCA/stock-logistics-warehouse#87]
Hi,
i've translated stock_reserve and stock_reserve_sale to german. Can you add them to the Repo?
stock_reserve: https://www.dropbox.com/s/wwa16gnvh0gu3m6/de.po?dl=0
stock_reserve_sale: https://www.dropbox.com/s/baz0aoqni94t1o1/de.po?dl=0
Thanks,
Robert Lieback

**Comment by pedrobaeza** [comment]
You can do it via a PR to this repo

**Comment by pedrobaeza** [comment]
Closing the issue as answered.
