### ISSUE TITLE
stock_available: translation issues on product.product view

### ISSUE THREAD

**Issue by gurneyalex** [OCA/stock-logistics-warehouse#89]
Steps to reproduce:
1. connect to v8 instance on https://runbot.odoo-community.org/runbot/repo/github-com-oca-stock-logistics-warehouse-153 
2. add French as a language on the instance
3. enable Technical Settings on Administrator
4. set French as Administrator language
5. Go to Ventes -> Variantes d'articles (Sales -> Product Variants)

Expected:

the "Available to promise" column header is translated to French

Actual: it is displayed in English. 

The translation is OK on the product.template views.

**Comment by gurneyalex** [comment]
@clonedagain could you look into this, please?

**Comment by clonedagain** [comment]
OK I'll give it a try but it may be delayed a bit, we're still fighting fires since we moved to v8.

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by clonedagain** [comment]
Sorry, We're not been doing much Odoo development lately.
@lbellier do you think we had we fixed this internally ?

**Comment by lbellier** [comment]
@clonedagain: No we didn't. I will fix that it asap.

**Comment by lbellier** [comment]
@clonedagain  and @pedrobaeza :
I have fixed it. You can find the pull request at the following link :
https://github.com/OCA/stock-logistics-warehouse/pull/212
