### ISSUE TITLE
[12] sale_stock_info_popup not showing products with serial number

### ISSUE THREAD

**Issue by JordiADARIA** [OCA/stock-logistics-warehouse#898]
Hi,

with sale_stock_info_popup module installed, its possible to see stock availability on sale order line, but it's showing "0" when product has **serial numbers assigned**...

thanks!

**Comment by pedrobaeza** [comment]
Serial numbers can't be assigned in sales orders, so you have an incompatible module. Any way, this doesn't seem a problem of this module, but the other.

**Comment by JordiADARIA** [comment]
Hi Pedro

no, i mean **not showing stock if the product has serial numbers**. Sorry, im not speaking about write serial numbers there.

**Comment by JordiADARIA** [comment]
![STOCK](https://user-images.githubusercontent.com/12151497/81053301-247b8e00-8ec5-11ea-81ae-105e17a258d5.jpg)

**Comment by JordiADARIA** [comment]
![OnSale](https://user-images.githubusercontent.com/12151497/81053563-9227ba00-8ec5-11ea-8d38-80aafbc8f44a.jpg)

**Comment by pedrobaeza** [comment]
I have products with tracking and this problem is not happening. Probably the warehouse in the sales order doesn't have that location included.

**Comment by JordiADARIA** [comment]
yes, all that things i already checked before.

For additional info, im on a multicompany setup. But ive checked all that configuration on both. It's really strange.

**Comment by pedrobaeza** [comment]
Are you able to reproduce the problem in runbot? Take into account that the code is taken from v13 feature, so if there's a bug here (maybe with multi-company), the same bug will apply to Odoo itself.

**Comment by JordiADARIA** [comment]
oh, no, let me check it there. ill check on a few hours, thanks Pedro.

**Comment by JordiADARIA** [comment]
ive checked it on runbot, and ### it's running completely right there... ill try to find on my instance and ill try to find the problem. If it's a "common" problem,ill come back here and ill publish it.

thanks!
