### ISSUE TITLE
Q: any module to compute qty by packaging for delivery?

### ISSUE THREAD

**Issue by simahawk** [OCA/stock-logistics-warehouse#910]
I need to compute the quantities to be picked for checkout by packaging. 

Eg: 855 units = 1 big box of 500 units + 3 boxes of 100 Units + 5 units

Is there such a module? If yes, I can't find it. If not, I can do it.

**Comment by rousseldenis** [comment]
@simahawk If you use packaging_uom in combination with sale packaging, it will use it in delivery moves. To be checked

**Comment by simahawk** [comment]
I've checked that module but I don't think is going to give me what I need.
I need to tell to the operator the combination of quantities by package unit / type to pick.
Eg: "1 big box + 3 boxes + 5 units" or "1 pallet, 3 boxes and 20 units" in one sentence, depending on the qty he/she has to pick.

IDK if I explained myself :sweat_smile:

**Comment by rousseldenis** [comment]
> I've checked that module but I don't think is going to give me what I need.
> I need to tell to the operator the combination of quantities by package unit / type to pick.
> Eg: "1 big box + 3 boxes + 5 units" or "1 pallet, 3 boxes and 20 units" in one sentence, depending on the qty he/she has to pick.
> 
> IDK if I explained myself

But I think your need is maybe more a module to compute the biggest packaging available to reduce packagings moves. Is that correct ?

So, when generating move lines (or pack operations <= v10), it should result in 3 lines with corresponding packagings. 

So, one move with qty = 855 => 3 move lines (1x 500, 3x 100, 5 x 1).

If I have correctly understood

**Comment by simahawk** [comment]
> But I think your need is maybe more a module to compute the biggest packaging available to reduce packagings moves. Is that correct ?

Nope. It's exactly the little thing I meant: show the picker a message. 
That's it. I don't want more lines nor automation whatsoever.
I have 1 single line w/ - say - 5305 units and I need to tell to the picker "pick 1 pallet, 3 boxes and 5 unit". 

Hope is more clear :)

**Comment by simahawk** [comment]
@rousseldenis this is what I had in mind: https://github.com/OCA/stock-logistics-warehouse/pull/911 :wink:

**Comment by rousseldenis** [comment]
> > But I think your need is maybe more a module to compute the biggest packaging available to reduce packagings moves. Is that correct ?
> 
> Nope. It's exactly the little thing I meant: show the picker a message.
> That's it. I don't want more lines nor automation whatsoever.
> I have 1 single line w/ - say - 5305 units and I need to tell to the picker "pick 1 pallet, 3 boxes and 5 unit".
> 
> Hope is more clear :)

It's a 'helper' message so. Ok, understood. That has to be clear in module, but LGTM

**Comment by rousseldenis** [comment]
Closing this as #911 is merged
