### ISSUE TITLE
Deduct request amount of product from product quantity in Inventory 

### ISSUE THREAD

**Issue by Zelelaw** [OCA/stock-logistics-warehouse#913]
I use this module and make a request to inventory. then check availability and amount deduction from a number of the product is still not working in my part is there any solution for this issue.

to be clear if we have 50 in quantity of one product the if I request 20 then this request must be checked to inventory for its availability and after received the product quantity should become 30.

**Comment by pedrobaeza** [comment]
Which module? Which version?

**Comment by Zelelaw** [comment]
sorry for not specifying this 
Version: Odoo Version 12
Module: stock_request

**Comment by Zelelaw** [comment]
Dear @pedrobaeza Waiting for you if any setting or configuration issue is there maybe if you know and willing to help me over the issue
with regards
Zelalem

**Comment by pedrobaeza** [comment]
Sorry, I only ask for issue completion, but can't say about the problem itself.

**Comment by Zelelaw** [comment]
Okay sir Thank you
