### ISSUE TITLE
[13.0] scrap_reason_code only set location if set

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/stock-logistics-warehouse#914]
@bodedra @AaronHForgeFlow 

def write and create currently assume that when a stock scrap is created or written with a reason_code_id set. This reason code has a location set. 
I run into issues when creating a scrap using the API because I don't have a location on the reason.

    def write(self, vals):
        if "reason_code_id" in vals:
            self.scrap_location_id = (
                self.env["reason.code"].browse(vals.get("reason_code_id")).location_id
            )
        return super(StockScrap, self).write(vals)

    @api.model
    def create(self, vals):
        if "reason_code_id" in vals:
            vals["scrap_location_id"] = (
                self.env["reason.code"]
                .browse(vals.get("reason_code_id"))
                .location_id.id
            )
        return super(StockScrap, self).create(vals)

I think it's better to only update the location if the reason has a location set?

**Comment by bodedra** [comment]
@CasVissers-360ERP I am agree with your point and here is PR #953

**Comment by CasVissers-360ERP** [comment]
Fixed in #953
