### ISSUE TITLE
No procurement rule found in location "..." for product "...". Check routes configuration (stock_mts_mto_rule)

### ISSUE THREAD

**Issue by yeestrada** [OCA/stock-logistics-warehouse#925]
Hello everybody, I am currently using Odoo 12, and I have installed stock_mts_mto_rule, I already have selected "Multi-Step Routes" and Make To Order + Make To Stock in the product form. Besides, I have created a Reordering Rule for the product but, when I make a sales and try to confirm it, the system shows me the error: 
**No procurement rule found in location "..." for product "...". Check routes configuration.**

Can anyone help me?

**Comment by niceboat000** [comment]
Hi yeestrada, this means your route is not closed-loop, pls check your route with odoo 12.0 document.
