### ISSUE TITLE
Back order

### ISSUE THREAD

**Issue by dominiquekonsuntack** [OCA/stock-logistics-warehouse#962]
module: stock_request
version: 12.0

**Steps to reproduce**
- create a stock request
- in the picking, do a partial delivery, this creates a back order

**Current behavior**
- the back order is not linked to stock request, so a user who wants to check the status of a stock request, will not "see" that there is a back order. He has to open the stock picking, and search manually for any backorder

**Expected behavior**
- it would be nice to see the back orders as well, no ?

**Comment by dominiquekonsuntack** [comment]
incidently, this would work well with the stock split module. A user makes a stock request. The delivery guy then decides to split the delivery, because of limited truck capacity.  The requestor then can see that he will be delivered in two trips instead of one trip.

**Comment by dominiquekonsuntack** [comment]
more specifically, the example above is for stock.request.order

**Comment by rousseldenis** [comment]
@JordiBForgeFlow @LoisRForgeFlow

**Comment by celm1990** [comment]
in v13 the happens same
