### ISSUE TITLE
[12.0] stock_quant_manual_assign destination package error on picking

### ISSUE THREAD

**Issue by conroyke56** [OCA/stock-logistics-warehouse#990]
Expected process, create quotation.
Confirm.
Picking Automatically generated and reserved.
Source packaging copied to destination packaging.
![create quotation](https://user-images.githubusercontent.com/33205454/96398586-f510d180-1217-11eb-921e-95e664f85a7b.PNG)
![pickign generated](https://user-images.githubusercontent.com/33205454/96398613-fd690c80-1217-11eb-87fe-269f3c62cc10.PNG)
![source package and destination package assigned](https://user-images.githubusercontent.com/33205454/96398625-0063fd00-1218-11eb-95ef-1dca88b60b26.PNG)

If manual assigned quant is used, destination packaging dissapears.
![assign manual quants and confirm](https://user-images.githubusercontent.com/33205454/96398651-1245a000-1218-11eb-85c7-f5b1f4de6dcc.PNG)

![destination package dissapears](https://user-images.githubusercontent.com/33205454/96398663-17a2ea80-1218-11eb-9b34-7cc7f8a2057d.PNG)

Any help would be much appreciated.

Thanks,

**Comment by rousseldenis** [comment]
@LoisRForgeFlow @pedrobaeza Could you help on this ?

**Comment by pedrobaeza** [comment]
I'm not using the module in this version.
