### ISSUE TITLE
12.0: [IMP] : stock_inventory_revaluation : improve the filter to search stock.location in unittest 

### ISSUE THREAD

**Issue by chandni299** [OCA/stock-logistics-warehouse#996]
in Unit test [at line 53](https://github.com/OCA/stock-logistics-warehouse/commit/50f3ddea4764514d597b992ad8144ed9d0e33466#diff-8cfc509c3b84591877162189d41e90d30f61ad1bd6d523eb8970690eb8191c64R53) we should improve the search domain by adding another filter as
`self.location = self.stock_location_model.search ([('location_id', '=', location.id), ('name', '=', 'Stock')])`
to make it more precise.
Reason: If I have more than one Warehouse having the same parent(location_id), then unit tests will get failed.

**Comment by rousseldenis** [comment]
> in Unit test [at line 53](https://github.com/OCA/stock-logistics-warehouse/commit/50f3ddea4764514d597b992ad8144ed9d0e33466#diff-8cfc509c3b84591877162189d41e90d30f61ad1bd6d523eb8970690eb8191c64R53) we should improve the search domain by adding another filter as
> `self.location = self.stock_location_model.search ([('location_id', '=', location.id), ('name', '=', 'Stock')])`
> to make it more precise.
> Reason: If I have more than one Warehouse having the same parent(location_id), then unit tests will get failed.

Either you have to point the error we have in an OCA travis build that would show an incompatibility between two OCA modules, either you are trying to test OCA modules with your proper install which is not recommended. As these modules are just 'aware' of the modules they depend on.

**Comment by chandni299** [comment]
Yes. I totally agree with you. It is just adding/improving the filter to make this search more precise and general to avoid failure for other use cases. I must name this issue as [IMP], not as [BUG].
